"""
MultiCloud MLOps - AWS Infrastructure Setup
Automates Section 7 of the manual guide.

Strategy: delegates the heavy lifting to the repo's own
scripts/setup-aws.sh (already well-tested), then adds:
  - Python-level credential verification
  - Resource URL retrieval and export to config
  - .env file generation for local testing

DynamoDB primary keys (match service code):
  guardian-videos  → video_id (S)
  guardian-events  → event_id (S)
"""
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from automation.config import config
from automation.utils.shell import aws, aws_json, get_logger, run, step, write_env_file

log = get_logger("aws")


# ─── 7.1 Credential verification ─────────────────────────────────────────────

def verify_aws_credentials() -> str:
    """Verify AWS CLI is configured and return account ID."""
    step("7.1 Configure / Verify AWS Credentials")
    try:
        identity = aws_json("sts", "get-caller-identity")
    except Exception:
        log.error(
            "AWS credentials not configured.\n"
            "Run: aws configure\n"
            "Or set AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_REGION in .env"
        )
        sys.exit(1)

    account_id = identity["Account"]
    region = aws("configure", "get", "region")

    config.aws.account_id = account_id
    config.aws.region = region or config.aws.region

    log.info("✅ AWS identity : %s", identity.get("Arn"))
    log.info("   Account ID  : %s", account_id)
    log.info("   Region      : %s", config.aws.region)
    return account_id


# ─── 7.2 Create AWS Resources via existing shell script ───────────────────────

def run_setup_script() -> None:
    """
    Execute scripts/setup-aws.sh (already in repo).
    This creates: S3 bucket, SQS queues, DynamoDB tables.
    """
    step("7.2 Create AWS Resources (S3, SQS, DynamoDB)")
    script_path = config.project_root / "scripts" / "setup-aws.sh"
    if not script_path.exists():
        log.error("scripts/setup-aws.sh not found at %s", script_path)
        sys.exit(1)

    # Ensure executable
    script_path.chmod(0o755)

    run(
        ["bash", str(script_path)],
        cwd=config.project_root,
        description="scripts/setup-aws.sh",
    )
    log.info("✅ AWS resources created via setup-aws.sh")


# ─── 7.3 Retrieve resource URLs ───────────────────────────────────────────────

def get_resource_urls(account_id: str) -> dict:
    """Retrieve created resource URLs/names and update config."""
    step("7.3 Get AWS Resource URLs")

    region = config.aws.region
    bucket_name = f"guardian-videos-{account_id[:8]}"

    # SQS URLs
    sqs_url = aws(
        "sqs", "get-queue-url",
        "--queue-name", "guardian-video-processing",
        "--region", region,
        "--query", "QueueUrl", "--output", "text",
    )
    gpu_url = aws(
        "sqs", "get-queue-url",
        "--queue-name", "guardian-gpu-processing",
        "--region", region,
        "--query", "QueueUrl", "--output", "text",
    )

    # DynamoDB table confirmation
    videos_table = aws(
        "dynamodb", "describe-table",
        "--table-name", "guardian-videos",
        "--region", region,
        "--query", "Table.TableName", "--output", "text",
    )
    events_table = aws(
        "dynamodb", "describe-table",
        "--table-name", "guardian-events",
        "--region", region,
        "--query", "Table.TableName", "--output", "text",
    )

    # Update config singleton
    config.aws.s3_bucket_name = bucket_name
    config.aws.sqs_queue_url = sqs_url
    config.aws.sqs_gpu_queue_url = gpu_url

    result = {
        "AWS_REGION":             region,
        "S3_BUCKET_NAME":         bucket_name,
        "SQS_QUEUE_URL":          sqs_url,
        "SQS_GPU_QUEUE_URL":      gpu_url,
        "DYNAMODB_VIDEOS_TABLE":  videos_table,
        "DYNAMODB_EVENTS_TABLE":  events_table,
    }

    log.info("  S3 bucket         : %s", bucket_name)
    log.info("  SQS video         : %s", sqs_url)
    log.info("  SQS gpu           : %s", gpu_url)
    log.info("  DynamoDB videos   : %s", videos_table)
    log.info("  DynamoDB events   : %s", events_table)
    return result


# ─── 7.4 Write .env ───────────────────────────────────────────────────────────

def write_local_env(resources: dict) -> None:
    """Write AWS resource values into .env for local service testing."""
    step("7.4 Write .env File for Local Testing")
    env_path = config.project_root / ".env"

    access_key = aws("configure", "get", "aws_access_key_id")
    secret_key  = aws("configure", "get", "aws_secret_access_key")

    values = {
        "# AWS Configuration (auto-generated by setup.py)": "",
        "AWS_ACCESS_KEY_ID":       access_key,
        "AWS_SECRET_ACCESS_KEY":   secret_key,
        "AWS_REGION":              resources["AWS_REGION"],
        "S3_BUCKET_NAME":          resources["S3_BUCKET_NAME"],
        "SQS_QUEUE_URL":           resources["SQS_QUEUE_URL"],
        "SQS_GPU_QUEUE_URL":       resources["SQS_GPU_QUEUE_URL"],
        "# DynamoDB": "",
        "DYNAMODB_VIDEOS_TABLE":   resources["DYNAMODB_VIDEOS_TABLE"],
        "DYNAMODB_EVENTS_TABLE":   resources["DYNAMODB_EVENTS_TABLE"],
        "# Policy Engine": "",
        "AUTO_APPROVE_THRESHOLD":  "0.2",
        "AUTO_REJECT_THRESHOLD":   "0.8",
        "LOG_LEVEL":               "INFO",
    }

    # Preserve any existing Azure/DevOps vars already in .env
    existing = {}
    if env_path.exists():
        for line in env_path.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, _, v = line.partition("=")
                k = k.strip()
                if k.startswith("AZURE") or k.startswith("AZDO"):
                    existing[k] = v.strip()

    with open(env_path, "w") as f:
        for k, v in values.items():
            if k.startswith("#"):
                f.write(f"\n{k}\n")
            else:
                f.write(f"{k}={v}\n")
        # Re-append preserved Azure vars
        if existing:
            f.write("\n# Azure / DevOps (preserved)\n")
            for k, v in existing.items():
                f.write(f"{k}={v}\n")

    log.info("✅ .env written to %s", env_path)
    log.warning("⚠  Never commit .env to git — it contains AWS credentials")


# ─── Entrypoint ───────────────────────────────────────────────────────────────

def setup_aws() -> dict:
    """Run full AWS setup. Returns resource URL dict for downstream stages."""
    log.info("=" * 62)
    log.info("  AWS Infrastructure Setup  (Section 7)")
    log.info("=" * 62)

    account_id = verify_aws_credentials()
    run_setup_script()
    resources = get_resource_urls(account_id)
    write_local_env(resources)

    log.info("=" * 62)
    log.info("  ✅ AWS setup complete")
    log.info("=" * 62)
    return {"account_id": account_id, **resources}


if __name__ == "__main__":
    setup_aws()
