"""Pydantic v2 schemas — the validation boundary for every structured payload."""

from app.schemas.catalog import (
    METRIC_DIRECTION,
    METRIC_LABEL,
    METRIC_SUBLABEL,
    Benchmarks,
    ComparisonRow,
    ContextWindow,
    Leaderboard,
    LeaderboardRow,
    ModelCard,
    ModelComparison,
)
from app.schemas.comparison import (
    BehaviouralCheck,
    BehaviouralScore,
    ComparisonReport,
    PromptComparison,
)
from app.schemas.dataset import DATASET_REGISTRY, DatasetInfo, dataset_relative_path, get_dataset
from app.schemas.evaluation import (
    EVAL_TARGET_INSTRUCTIONS,
    EVALUATOR_GROUPS,
    SYNTHETIC_PROMPT,
    ClusterAnalysis,
    ClusterSuggestion,
    EvaluationRun,
    EvaluatorResult,
    SyntheticDataset,
    SyntheticRow,
    default_evaluators,
)
from app.schemas.finetune import (
    Checkpoint,
    FineTuneJob,
    FineTuneJobConfig,
    Hyperparameters,
    JobLogEntry,
    JobMetrics,
    JobStatus,
    TrainingCostEstimate,
)
from app.schemas.training import (
    ChatMessage,
    RowError,
    TrainingRecord,
    ValidationReport,
    validate_jsonl_text,
)

__all__ = [
    "DATASET_REGISTRY",
    "EVALUATOR_GROUPS",
    "EVAL_TARGET_INSTRUCTIONS",
    "METRIC_DIRECTION",
    "METRIC_LABEL",
    "METRIC_SUBLABEL",
    "SYNTHETIC_PROMPT",
    "BehaviouralCheck",
    "BehaviouralScore",
    "Benchmarks",
    "ChatMessage",
    "Checkpoint",
    "ClusterAnalysis",
    "ClusterSuggestion",
    "ComparisonReport",
    "ComparisonRow",
    "ContextWindow",
    "DatasetInfo",
    "EvaluationRun",
    "EvaluatorResult",
    "FineTuneJob",
    "FineTuneJobConfig",
    "Hyperparameters",
    "JobLogEntry",
    "JobMetrics",
    "JobStatus",
    "Leaderboard",
    "LeaderboardRow",
    "ModelCard",
    "ModelComparison",
    "PromptComparison",
    "RowError",
    "SyntheticDataset",
    "SyntheticRow",
    "TrainingCostEstimate",
    "TrainingRecord",
    "ValidationReport",
    "dataset_relative_path",
    "default_evaluators",
    "get_dataset",
    "validate_jsonl_text",
]
