#!/usr/bin/env bash
#
# Phase 0 wizard, script 1 of 4 — Provisioning.
# Generated by the /wizard skill for Azure-Banking-Voice-Agentic-AI.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit it.
#
# WHY FOUR SCRIPTS, NOT ONE
#   Phase 0 (docs/PLAN.md) spans real-world waits a single sitting can't absorb: 3 test calls today,
#   then a 24h wait for Cost Analysis to populate, then a 72h idle-billing observation window before
#   teardown. Four scripts, run on their own days, handing state forward via a shared .env.phase0:
#     01-provision.sh          (today)      — this script. Pre-checks, the hard gate, all provisioning.
#     02-test-calls.sh         (today, after 01) — 3 real calls from your mobile; measures the meters.
#     03-cost-check-24h.sh     (tomorrow)   — reads real Cost Analysis, sanity-checks against estimate.
#     04-teardown-and-r08.sh   (+72h from provisioning) — idle billing verdict, R-08, ADRs, teardown.
#
# WHAT THIS SCRIPT AUTOMATES vs WHAT ONLY YOU CAN DO
#   Everything in this script is Azure CLI / REST calls this wizard runs FOR you — confirmed at each
#   state-changing step. The only things only you can do live in 02-test-calls.sh (dialing a real phone)
#   and in the elapsed-time waits between scripts 1→3→4. This script provisions and then stops; it does
#   not dial anything.
#
# HARD GATE — restated verbatim from CLAUDE.md, because CLAUDE.md requires that:
#   "No billable Azure resource is created without Marco typing `APPROVED: <phase name>`... Never
#   auto-accept a diff that provisions a billable resource... no exceptions, no partial provisioning
#   ahead of it."
#   Stages before the gate below are read-only (provider status, Models API). Nothing that creates,
#   modifies, or spends is called before you type the exact string `APPROVED: Phase 0`.
#
# KNOWN VERIFICATION ITEMS — flagged instead of guessed, per this project's own "verify, don't assume"
# rule (R-01 already burned it once on an unverified regional claim). Each is marked VERIFY inline too:
#   1. Models API `api-version` for the deprecationDate query (stage 2) — confirm the version this
#      wizard uses still returns a 200; if not, check the AI Foundry portal's Models page instead.
#   2. List Area Codes REST path/api-version (stage 8) — Communication Services phone number APIs move
#      fast; confirm against the current Azure REST API reference before running that stage.
#   3. The exact `azure-communication-callautomation` SDK parameter/enum names in the generated echo app
#      (stage 11) — written against the shapes documented in docs/PLAN.md's "Architecture" section
#      (verified), but the SDK's Python class/enum names for MediaStreamingOptions were not independently
#      re-verified for this wizard. Check them against the installed package version's docs before
#      building the container image.
#
# COST NOTE NOT IN docs/PLAN.md's BUDGET TABLE: `az containerapp up --source` auto-provisions a Basic
# Azure Container Registry (~$5/mo) if you let it pick a registry. That is real, unbudgeted fixed cost
# against the $25 ceiling. This script avoids it — it builds locally and pushes to Docker Hub's free
# tier instead, and points Container Apps at that external image. Flagged here because it's the kind of
# thing that's easy to wave through without noticing it changed the budget.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env.phase0}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard runs Azure CLI/REST calls on your behalf and confirms before anything\n' "$DIM"
  printf '  billable happens. Stop any time with Ctrl-C and re-run later — it remembers values\n'
  printf '  already saved in %s.%s\n' "$ENV_FILE" "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
err()  { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# require_gate — the CLAUDE.md hard gate. Blocks until the human types the exact phrase.
require_gate() {
  local phrase="$1" reply=""
  printf '\n'
  warn "HARD GATE — nothing past this point is free. Everything below creates or spends against"
  warn "the \$25/month ceiling. This is the stop CLAUDE.md requires before any billable resource."
  printf '\n'
  while true; do
    printf '  %sType exactly (case-sensitive):%s %s%s%s\n  > ' "$BOLD" "$RESET" "$BOLD" "$phrase" "$RESET"
    read -r reply || true
    if [[ "$reply" == "$phrase" ]]; then
      ok "gate passed — proceeding"
      return 0
    fi
    err "that didn't match \"$phrase\" exactly. Ctrl-C to stop, or try again."
  done
}

finish() {
  _clear
  printf '\n%s%s  ✓ Script complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Fixed identifiers for this project. Change here if you want different names before running —
# not something worth a prompt each run.
SUBSCRIPTION_ID="960936b9-ecde-465b-be8d-776ca077dcd0"
LOCATION="canadacentral"
RESOURCE_GROUP="rg-azure-banking-voice-agentic-ai"
AOAI_NAME="aoai-azure-banking-voice-cc"
ACS_NAME="acs-azure-banking-voice"
CAE_NAME="cae-azure-banking-voice-p0"
CONTAINERAPP_NAME="ca-azbank-echo-p0"
MODEL_NAME="gpt-realtime-mini"
MODEL_VERSION="2025-10-06"          # the GA version this project pins to (decision 14, revised
                                     # 2026-08-20 from 2025-12-15/isDefaultVersion after the live
                                     # Models API pull showed 2025-10-06 has ~3.7 more months of
                                     # runway at identical audio-token pricing — see PLAN.md decision 14
MODEL_VERSION_OLD="2025-12-15"      # the isDefaultVersion — retires 2026-12-15, ~4mo out; not pinned
DEPLOYMENT_NAME="gpt-realtime-mini" # deployment name == model name, matching B3's allowlist string

REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"   # docs/phase0/wizard -> project root
FINDINGS_FILE="$SCRIPT_DIR/../findings.md"
ADR_DIR="$REPO_ROOT/docs/adr"

# on_error — fires on any unexpected command failure (set -e / ERR trap), and is also called
# explicitly by the post-deploy health check below. Reports exactly what exists in $RESOURCE_GROUP
# at the moment of failure, and offers to delete the Container App/environment right then if either
# made it into existence — the two resources that actually bill per-hour, as opposed to the ACS
# resource, AOAI resource+deployment, and phone number, which are either free to hold idle or
# deliberately kept (the number). Exists because a script that dies mid-provisioning with no cleanup
# path is exactly how "no billable resource without approval" quietly becomes "one nobody's watching".
on_error() {
  local exit_code="${1:-$?}"
  _clear
  printf '\n%s%s  ✗ 01-provision.sh failed at stage %s/%s (exit %s)%s\n\n' \
    "$BOLD" "$RED" "$_STAGE_INDEX" "$TOTAL_STAGES" "$exit_code" "$RESET"
  say "Resources that exist in $RESOURCE_GROUP right now:"
  # --location "" overrides any stale `az config`/`~/.azure/config` defaults.location — without it,
  # a machine with a non-canadacentral/global default silently returns an empty table here even
  # while the Container App is billing. Found 2026-08-21; see docs/phase0/findings.md.
  az resource list --resource-group "$RESOURCE_GROUP" --location "" --output table 2>/dev/null \
    || note "(resource group itself doesn't exist yet, or the query failed — nothing billable then)"
  printf '\n'
  note "Only two things here bill per-hour: a Container App (min-replicas=1) and its environment."
  note "Everything else (resource group, ACS resource, AOAI resource+deployment, the phone number)"
  note "is either free to hold idle or deliberately kept — leaving those is not a problem."
  if az containerapp show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
    warn "Container App $CONTAINERAPP_NAME exists and is billing right now."
    if confirm "Delete it now? (safe — fix the cause and re-run this script from the top afterward)"; then
      az containerapp delete --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" --yes --output none 2>/dev/null || true
      az containerapp env delete --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --yes --output none 2>/dev/null || true
      ok "deleted — re-run 01-provision.sh from the top once you've fixed the cause above"
    else
      warn "left running — it is billing until you delete it or re-run this script to completion."
    fi
  else
    ok "no Container App exists yet — nothing here is billing beyond the number (by design)"
  fi
  exit "$exit_code"
}
trap 'on_error $?' ERR

banner "Azure-Banking-Voice-Agentic-AI — Phase 0, script 1/4: Provisioning"

# ── Stage 1: pre-flight (free, read-only) ──────────────────────────────────
stage "Pre-flight checks (free, read-only)"
say "Confirming tools and the correct subscription before anything else."

for tool in az curl docker python3; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    err "$tool not found on PATH — install it before continuing."
    exit 1
  fi
done
ok "az, curl, docker, python3 all present"

CURRENT_SUB=$(az account show --query id -o tsv 2>/dev/null || true)
if [[ "$CURRENT_SUB" != "$SUBSCRIPTION_ID" ]]; then
  warn "az is on subscription $CURRENT_SUB, expected $SUBSCRIPTION_ID"
  if confirm "Switch to it now (az account set)?"; then
    az account set --subscription "$SUBSCRIPTION_ID"
    ok "switched"
  else
    err "wrong subscription — stopping rather than provisioning in the wrong place."
    exit 1
  fi
else
  ok "az is on the correct subscription ($SUBSCRIPTION_ID)"
fi

SPENDING_LIMIT=$(az account show --query "spendingLimit" -o tsv 2>/dev/null || echo "unknown")
note "spendingLimit: $SPENDING_LIMIT — CLAUDE.md/PLAN.md record this as Off. Azure will not stop spend."
note "at any threshold; B4 (call-length/daily-cap) is the only brake. Confirm this still says Off."

REGISTRATION_STATE=$(az provider show --namespace Microsoft.Communication --query "registrationState" -o tsv 2>/dev/null || echo "NotRegistered")
note "Microsoft.Communication registration state: $REGISTRATION_STATE"

EXISTING_RG=$(az group exists --name "$RESOURCE_GROUP" 2>/dev/null || echo "false")
if [[ "$EXISTING_RG" == "true" ]]; then
  warn "resource group $RESOURCE_GROUP already exists — this wizard assumes a clean start."
  say "docs/handoffs/2026-08-19-scoping-complete-phase0-pending.md records the subscription as bare"
  say "(zero resource groups). If this is a re-run after a partial attempt, that's fine; if it's"
  say "unexpected, stop and find out what's in it before continuing."
  confirm "Continue anyway?" || exit 1
else
  ok "resource group $RESOURCE_GROUP does not exist yet — clean start confirmed"
fi

write_env "SUBSCRIPTION_ID" "$SUBSCRIPTION_ID"
write_env "RESOURCE_GROUP" "$RESOURCE_GROUP"
write_env "LOCATION" "$LOCATION"
write_env "CONTAINERAPP_NAME" "$CONTAINERAPP_NAME"
write_env "CAE_NAME" "$CAE_NAME"
# PROVISION_TIME is deliberately NOT written here, and not by this script at all anymore.
# 04-teardown-and-r08.sh uses it to anchor R-04's 72h idle-billing observation window; that window
# is now anchored in 02-test-calls.sh, gated on a confirmed answered call rather than on this
# script's healthz check -- see Stage 12's note and docs/phase0/findings.md,
# "healthz-as-window-gate".

# ── Stage 2: R-01 — Models API deprecationDate check (free, read-only) ─────
stage "R-01 — verify gpt-realtime-mini retirement dates via the Models API"
say "Originally: docs/PLAN.md recorded this model listed TWICE with conflicting retirement dates per"
say "version (2025-10-06 as 2027-04-06 or 2026-09-21; 2025-12-15 as 2027-06-15 or 2026-12-15)."
say "Resolved 2026-08-20 by a live query: 2025-10-06 -> 2027-04-06, 2025-12-15 -> 2026-12-15 — the"
say "pessimistic case in both, confirmed real. Decision 14 was revised to pin 2025-10-06 on that"
say "basis (~3.7 more months of runway, identical cost). Re-querying now to reconfirm it still holds —"
say "dates on a live catalog can move, and this pin decision deserves the same live check every time"
say "this script runs, not just the one that found it."
warn "VERIFY: api-version below (2023-05-01) against the current Azure REST API reference before"
warn "trusting a non-200 response as \"not available\" rather than \"wrong api-version\"."

MODELS_JSON=$(az rest --method get \
  --url "https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/providers/Microsoft.CognitiveServices/locations/${LOCATION}/models?api-version=2023-05-01" \
  2>/dev/null || echo '{}')

R01_FINDING=$(python3 - "$MODELS_JSON" "$MODEL_NAME" <<'PYEOF'
import json, sys
data = json.loads(sys.argv[1] or "{}")
name = sys.argv[2]
rows = []
for m in data.get("value", []):
    model = m.get("model", {})
    if model.get("name") == name:
        rows.append({
            "version": model.get("version"),
            "deprecationDate": model.get("deprecation", {}) or model.get("lifecycleStatus"),
            "raw": model,
        })
print(json.dumps(rows, indent=2, default=str))
PYEOF
)
say "Matching entries for $MODEL_NAME in $LOCATION:"
printf '%s\n' "$R01_FINDING" | sed 's/^/    /'
if [[ "$R01_FINDING" == "[]" ]]; then
  warn "no rows matched — either the model isn't listed for $LOCATION, or the api-version needs updating."
  warn "Cross-check manually: AI Foundry portal → Models → filter to $LOCATION → $MODEL_NAME."
fi
{
  echo "## R-01 — Models API deprecation-date check"
  echo ""
  echo "Queried $(date -u +%Y-%m-%dT%H:%M:%SZ) against location=$LOCATION."
  echo '```json'
  printf '%s\n' "$R01_FINDING"
  echo '```'
  echo ""
} >> "$FINDINGS_FILE"
ok "recorded to $FINDINGS_FILE"
pause "Review the finding above, then press Enter to continue."

# ── Stage 3: THE HARD GATE ──────────────────────────────────────────────────
stage "HARD GATE — nothing billable happens without your explicit approval"
_clear
printf '\n%s%s  STOP CONDITIONS — restated verbatim from CLAUDE.md, per its own requirement%s\n\n' "$BOLD" "$RED" "$RESET"
cat <<'EOF'
  - No phase begins without written exit criteria from the prior phase and Marco's explicit approval.
  - No billable Azure resource is created without Marco typing `APPROVED: <phase name>`.
  - Never auto-accept a diff that provisions a billable resource, or that touches `dispatch/gate.py`
    (B1) or anything on the DTMF/PIN path (B2). These always get a human look before they land, no
    matter how mechanical the change appears.
  - `PROJECT_STATE.md` is updated before any session ends, and never exceeds its size ceiling.
  - Restate these conditions verbatim at the top of every session summary and after every `/compact`.
EOF
printf '\n'
say "Everything up to here (pre-flight, R-01 check) was read-only — zero dollars spent."
say "Everything from here on registers a provider, creates resources, purchases a phone number, and"
say "deploys compute. All of it is reversible except the number's ongoing \$1/mo (kept by design)."
require_gate "APPROVED: Phase 0"

# ── Stage 4: register Microsoft.Communication ───────────────────────────────
stage "Register Microsoft.Communication resource provider"
if [[ "$REGISTRATION_STATE" == "Registered" ]]; then
  ok "already registered"
else
  say "Registering (no cost — this is a subscription-level flag, not a resource)."
  az provider register --namespace Microsoft.Communication
  say "Polling until Registered (can take a couple of minutes)..."
  for _ in $(seq 1 30); do
    STATE=$(az provider show --namespace Microsoft.Communication --query registrationState -o tsv)
    [[ "$STATE" == "Registered" ]] && break
    sleep 10
  done
  if [[ "$STATE" == "Registered" ]]; then
    ok "Microsoft.Communication registered"
  else
    err "still $STATE after 5 minutes of polling — check az provider show manually before continuing."
    exit 1
  fi
fi

# ── Stage 5: resource group + Azure OpenAI resource ─────────────────────────
stage "Create resource group and the Azure OpenAI resource (Canada Central)"
say "Per decision 12 (docs/PLAN.md): Canada Central, no fallback. If this fails because realtime"
say "isn't servable here, STOP and report — do not let this wizard relocate the region for you."

az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none
ok "resource group $RESOURCE_GROUP ready"

if az cognitiveservices account show --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  ok "Azure OpenAI resource $AOAI_NAME already exists"
else
  az cognitiveservices account create \
    --name "$AOAI_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --kind OpenAI \
    --sku S0 \
    --custom-domain "$AOAI_NAME" \
    --output none
  ok "Azure OpenAI resource $AOAI_NAME created"
fi
AOAI_ENDPOINT=$(az cognitiveservices account show --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" --query properties.endpoint -o tsv)
write_env "AOAI_NAME" "$AOAI_NAME"
write_env "AOAI_ENDPOINT" "$AOAI_ENDPOINT"

# ── Stage 6: R-06 — attempt a DataZoneStandard deployment ───────────────────
stage "R-06 — attempt a DataZoneStandard realtime deployment (confirm/deny)"
say "docs/PLAN.md: pricing feed lists DataZoneStandard realtime meters, but availability tables show"
say "Global Standard only for realtime models. This is the live test that actually settles it."
say "This is a genuine attempt at a billable deployment — if it succeeds, it will be deleted right"
say "after (decision 14 pins GlobalStandard; DataZone here is a probe, not what stays in service)."

# No confirm gate on this probe (unlike Stage 9's purchase) -- deliberately guarded on the findings.md
# section instead, since re-running this stage with no guard would re-attempt a real billable-deployment
# API call every single time and duplicate-append this section on every run. Skip once R-06 is answered.
if grep -q "^## R-06" "$FINDINGS_FILE" 2>/dev/null; then
  ok "R-06 already answered in $FINDINGS_FILE, skipping the probe re-attempt"
  # Stage 10's R06_LINE (line ~719) reads $DATAZONE_OK under `set -u` with no default -- must stay
  # set on the skip path too, or a re-run crashes there instead of at this stage. Reconstructed from
  # the persisted R06_ANSWER_SHORT rather than left unbound.
  DATAZONE_OK=$([[ "$(_existing "R06_ANSWER_SHORT" || true)" == "OFFERED" ]] && echo 1 || echo 0)
else

DATAZONE_RESULT=$(az cognitiveservices account deployment create \
  --name "$AOAI_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --deployment-name "${DEPLOYMENT_NAME}-datazone-probe" \
  --model-name "$MODEL_NAME" \
  --model-version "$MODEL_VERSION" \
  --model-format OpenAI \
  --sku-name DataZoneStandard \
  --sku-capacity 1 \
  2>&1) && DATAZONE_OK=1 || DATAZONE_OK=0

if [[ "$DATAZONE_OK" == "1" ]]; then
  warn "DataZoneStandard deployment SUCCEEDED — this contradicts docs/PLAN.md's ADR-001 assumption."
  warn "Deleting the probe deployment now (GlobalStandard is still what stays in service per decision 14)."
  az cognitiveservices account deployment delete \
    --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" \
    --deployment-name "${DEPLOYMENT_NAME}-datazone-probe" --output none || true
  R06_ANSWER="OFFERED — DataZoneStandard deployment of $MODEL_NAME succeeded in $LOCATION. This is a surprise relative to the plan's assumption; flag to Marco before ADR-001 is finalized on the old assumption."
else
  ok "DataZoneStandard deployment failed, as the plan predicted — confirming R-06."
  R06_ANSWER="NOT OFFERED — confirmed empirically. Attempt failed with:
$(printf '%s\n' "$DATAZONE_RESULT" | tail -20)"
fi
{
  echo "## R-06 — DataZoneStandard deployment probe"
  echo ""
  echo "$R06_ANSWER"
  echo ""
} >> "$FINDINGS_FILE"
write_env "R06_ANSWER_SHORT" "$([[ "$DATAZONE_OK" == "1" ]] && echo OFFERED || echo NOT_OFFERED)"
ok "recorded to $FINDINGS_FILE"
fi

# ── Stage 7: the real GlobalStandard deployment ──────────────────────────────
stage "Create the real gpt-realtime-mini deployment (GlobalStandard, NoAutoUpgrade)"
say "This is the deployment the rest of the project actually uses. Model pin per decision 14."

if az cognitiveservices account deployment show \
    --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" --deployment-name "$DEPLOYMENT_NAME" >/dev/null 2>&1; then
  ok "deployment $DEPLOYMENT_NAME already exists"
else
  az cognitiveservices account deployment create \
    --name "$AOAI_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --deployment-name "$DEPLOYMENT_NAME" \
    --model-name "$MODEL_NAME" \
    --model-version "$MODEL_VERSION" \
    --model-format OpenAI \
    --sku-name GlobalStandard \
    --sku-capacity 1 \
    --output none
  ok "deployment $DEPLOYMENT_NAME created (GlobalStandard)"
fi

# version-upgrade-option isn't a create-time flag at all on this CLI's `az cognitiveservices account
# deployment` group (only create/delete/list/show exist — confirmed live, azure-cli 2.87.0), and there
# is no `update` subcommand to fall back to either, contrary to what this script originally assumed.
# Checked/set unconditionally (not just on fresh create) via a direct ARM PATCH, so a deployment that
# already existed from an earlier partial run also gets brought into compliance with B3's NoAutoUpgrade
# requirement rather than silently left on whatever default the API assigned (observed:
# OnceNewDefaultVersionAvailable — the opposite of what B3 requires).
CURRENT_UPGRADE_OPT=$(az cognitiveservices account deployment show \
  --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" --deployment-name "$DEPLOYMENT_NAME" \
  --query properties.versionUpgradeOption -o tsv 2>/dev/null || true)
if [[ "$CURRENT_UPGRADE_OPT" != "NoAutoUpgrade" ]]; then
  note "versionUpgradeOption is '$CURRENT_UPGRADE_OPT', not NoAutoUpgrade — patching via ARM REST."
  DEPLOYMENT_ID="/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$AOAI_NAME/deployments/$DEPLOYMENT_NAME"
  az rest --method patch \
    --url "https://management.azure.com${DEPLOYMENT_ID}?api-version=2026-07-01" \
    --body '{"properties":{"versionUpgradeOption":"NoAutoUpgrade"}}' \
    --headers "Content-Type=application/json" \
    --output none \
    || { err "couldn't set versionUpgradeOption via ARM REST either — verify NoAutoUpgrade in the portal before Phase 1, do not assume it's set."; exit 1; }
  ok "versionUpgradeOption set to NoAutoUpgrade (B3 requirement)"
else
  ok "versionUpgradeOption already NoAutoUpgrade"
fi
write_env "DEPLOYMENT_NAME" "$DEPLOYMENT_NAME"
write_env "MODEL_VERSION" "$MODEL_VERSION"

# ── Stage 8: ACS resource + List Area Codes (R-05) ───────────────────────────
stage "Create the ACS resource and check live Toronto-area number inventory (R-05)"
say "location: 'global' (ACS control plane isn't regional); dataLocation: 'Canada' (decision 12/ADR-002)."

if az communication list --resource-group "$RESOURCE_GROUP" --query "[?name=='$ACS_NAME']" -o tsv | grep -q .; then
  ok "ACS resource $ACS_NAME already exists"
else
  # --location must stay explicit below — `az communication create --help` confirms this command
  # falls back to `az config`'s defaults.location (currently a stale "eastus" on this machine) when
  # omitted. Don't let a future edit drop it. Placed above the command, not between its
  # backslash-continued args: a comment line mid-continuation silently truncates the command instead
  # of erroring (confirmed empirically, docs/phase0/findings.md) — everything after it, including
  # --location itself, would be dropped, which is exactly the failure this comment warns against.
  az communication create \
    --name "$ACS_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --location "global" \
    --data-location "Canada" \
    --output none
  ok "ACS resource $ACS_NAME created"
fi

# api-version corrected 2026-08-20: 2022-01-11-preview2 returned a live 400 UnsupportedApiVersion.
# Verified current GA version against the Microsoft Learn REST reference (List Area Codes,
# rest-communication-phonenumbers-2025-06-01) rather than re-guessing — query parameters unchanged,
# only the version string moved. Re-verify this again if it ever 400s the same way; api-versions here
# have moved before and will again.
ACS_API_VERSION="2025-06-01"
ACS_TOKEN=$(az account get-access-token --resource "https://communication.azure.com" --query accessToken -o tsv)
ACS_HOST="${ACS_NAME}.canada.communication.azure.com"

AREA_CODES_JSON=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
  "https://${ACS_HOST}/availablePhoneNumbers/countries/CA/areaCodes?api-version=${ACS_API_VERSION}&phoneNumberType=geographic&assignmentType=application&locality=Toronto&administrativeDivision=ON")

say "Area codes returned for locality=Toronto, administrativeDivision=ON:"
printf '%s\n' "$AREA_CODES_JSON" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$AREA_CODES_JSON"

# A 404 here means the locality itself isn't in ACS's inventory (confirmed live 2026-08-20: Toronto is
# absent from the entire country-wide locality list, not just filtered out for ON) -- not necessarily
# that codes are all taken. Pull the real locality list too, every time, so a "no results" reading
# never gets mistaken for "sold out" without the operator seeing what actually IS available.
if printf '%s' "$AREA_CODES_JSON" | grep -q '"NotFound"'; then
  warn "No area codes for locality=Toronto — pulling the real available-locality list instead of guessing why."
fi
LOCALITIES_JSON=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
  "https://${ACS_HOST}/availablePhoneNumbers/countries/CA/localities?api-version=${ACS_API_VERSION}&maxPageSize=100")
say "All Canada-wide geographic localities currently in ACS's inventory (unfiltered):"
printf '%s\n' "$LOCALITIES_JSON" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$LOCALITIES_JSON"

{
  echo "## R-05 — live Toronto-area area-code inventory"
  echo ""
  echo "Query: locality=Toronto, administrativeDivision=ON, phoneNumberType=geographic,"
  echo "assignmentType=application, api-version=${ACS_API_VERSION}"
  echo '```json'
  printf '%s\n' "$AREA_CODES_JSON"
  echo '```'
  echo ""
  echo "All Canada-wide geographic localities in ACS's inventory (unfiltered, maxPageSize=100):"
  echo '```json'
  printf '%s\n' "$LOCALITIES_JSON"
  echo '```'
  echo ""
} >> "$FINDINGS_FILE"
ok "recorded to $FINDINGS_FILE"
write_env "ACS_NAME" "$ACS_NAME"
pause "Review the area codes above — you'll pick one in the next stage. Press Enter to continue."

# ── Stage 9: purchase the number ─────────────────────────────────────────────
stage "Purchase a Canada local geographic number"

# R-09 in practice: a second purchase is permanent (this rule forbids ever releasing either number),
# so this stage must never re-run its search/purchase logic once PHONE_NUMBER is set -- not "usually
# skip", structurally cannot reach the purchase call at all when it's already set. Read directly from
# ENV_FILE via _existing (same mechanism ask()/ask_secret() use), not trusted from a shell variable
# that might not be populated on a fresh invocation of this script.
if [[ -n "$(_existing "PHONE_NUMBER" || true)" ]]; then
  ok "already purchased, skipping: $(_existing "PHONE_NUMBER") (PHONE_NUMBER set in $ENV_FILE)"
  note "R-09: this number is never released by any script, so a re-run never re-purchases while"
  note "PHONE_NUMBER is set. Delete it from .env.phase0 yourself if you genuinely need a new search --"
  note "never as an accidental side effect of re-running this script."
else

# Hard precondition: phone number purchase is a Microsoft.Communication data-plane operation and
# fails if the provider hasn't finished registering yet. Stage 4 kicked registration off and polled
# for up to 5 minutes, but registration can legitimately still be in flight past that window (it was
# already "Registering" at Stage 1 before this script touched it, from outside this session) — so this
# is checked again, right here, rather than trusted from Stage 4's earlier poll. Failing here with a
# clear message beats the same failure surfacing as an opaque 4xx from the phone-number search API.
say "Confirming Microsoft.Communication has actually reached Registered before attempting a purchase —"
say "this failed opaquely from the phone-number API before this check existed."
CURRENT_REG_STATE=$(az provider show --namespace Microsoft.Communication --query "registrationState" -o tsv)
if [[ "$CURRENT_REG_STATE" != "Registered" ]]; then
  err "Microsoft.Communication is '$CURRENT_REG_STATE', not 'Registered' — a purchase attempt would"
  err "fail here with a confusing API error instead. Waiting up to 3 more minutes, then stopping if it"
  err "hasn't settled (registration can occasionally take longer than Stage 4's own poll window)."
  for _ in $(seq 1 18); do
    CURRENT_REG_STATE=$(az provider show --namespace Microsoft.Communication --query "registrationState" -o tsv)
    [[ "$CURRENT_REG_STATE" == "Registered" ]] && break
    sleep 10
  done
  if [[ "$CURRENT_REG_STATE" != "Registered" ]]; then
    err "still '$CURRENT_REG_STATE' — stopping rather than hitting an opaque error at the purchase call."
    err "Check manually: az provider show --namespace Microsoft.Communication --query registrationState"
    err "Re-run this script once it shows 'Registered'; everything before this stage is idempotent."
    exit 1
  fi
fi
ok "Microsoft.Communication is Registered — safe to purchase"

say "\$0.0085/min inbound, single national Canada rate — confirmed unaffected by area code (Microsoft's"
say "PSTN pricing doc has no regional breakdown; docs/phase0/findings.md, 'R-05 supplemental')."
say "\$1.00/mo, ongoing — this is the one resource that survives today's teardown, by design."
# Default is 705 (North Bay/Sault Ste Marie, ON) per decision 13's 2026-08-20 revision -- Toronto
# (416/647/437/905/289) is confirmed absent from ACS's Canadian geographic inventory (R-05), and
# Guelph (226), the first-considered fallback, evaporated from that same inventory mid-session. Still
# a free-text prompt, not hardcoded -- inventory has proven volatile enough this session (a locality
# vanishing in ~20min) that it must be re-confirmed live, not trusted from an earlier plan.
ask AREA_CODE "Which area code do you want to search+purchase? [decision 13: 705]"
AREA_CODE="${AREA_CODE:-705}"

warn "About to search + reserve + purchase a real number in area code $AREA_CODE. This starts billing."
confirm "Confirm: search and purchase a $AREA_CODE number now?" || { err "stopped — re-run this stage when ready."; exit 1; }

# api-version corrected 2026-08-20, same fix as Stages 7/8 -- 2022-01-11-preview2 is stale and 400s.
SEARCH_RESULT=$(curl -s -X POST -H "Authorization: Bearer $ACS_TOKEN" -H "Content-Type: application/json" \
  "https://${ACS_NAME}.canada.communication.azure.com/availablePhoneNumbers/countries/CA/:search?api-version=2025-06-01" \
  -d "{\"phoneNumberType\":\"geographic\",\"assignmentType\":\"application\",\"capabilities\":{\"calling\":\"inbound\",\"sms\":\"none\"},\"areaCode\":\"$AREA_CODE\",\"quantity\":1}")
SEARCH_ID=$(printf '%s' "$SEARCH_RESULT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("searchId",""))' 2>/dev/null || true)

if [[ -z "$SEARCH_ID" ]]; then
  err "search didn't return a searchId — raw response:"
  printf '%s\n' "$SEARCH_RESULT" | sed 's/^/    /'
  exit 1
fi
say "Search reserved a number under searchId $SEARCH_ID. Purchasing it now."
say "Reserved number and rate — CONFIRM before this goes further:"
printf '%s\n' "$SEARCH_RESULT" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$SEARCH_RESULT"

CANDIDATE_NUMBER=$(printf '%s' "$SEARCH_RESULT" | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("phoneNumbers") or [""])[0])' 2>/dev/null || true)

# Purchase is itself async (202 + Operation-Location, same shape as search) -- polled properly below
# rather than a blind sleep-then-hope, so a real failure (R-09: the number this searchId reserved can
# evaporate between search and purchase, same as Guelph did between two checks 20min apart this
# session -- see docs/phase0/findings.md) is detected and reported, not silently missed.
PURCHASE_HEADERS=$(curl -s -D - -o /dev/null -X POST -H "Authorization: Bearer $ACS_TOKEN" \
  "https://${ACS_NAME}.canada.communication.azure.com/availablePhoneNumbers/:purchase?api-version=2025-06-01" \
  -d "{\"searchId\":\"$SEARCH_ID\"}" -H "Content-Type: application/json")
OPERATION_ID=$(printf '%s' "$PURCHASE_HEADERS" | tr -d '\r' | sed -n 's/^operation-id: //Ip')

if [[ -z "$OPERATION_ID" ]]; then
  err "purchase call didn't return an operation-id — raw headers:"
  printf '%s\n' "$PURCHASE_HEADERS" | sed 's/^/    /'
  err "Do not assume the purchase went through either way. Check the Azure portal (ACS resource ->"
  err "Phone Numbers) manually before re-running this stage, to avoid a double-purchase attempt."
  exit 1
fi

say "Purchase submitted (operation $OPERATION_ID). Polling for completion — this can take up to a minute."
PURCHASE_STATUS="notStarted"
for _ in $(seq 1 18); do
  OP_RESULT=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
    "https://${ACS_NAME}.canada.communication.azure.com/phoneNumbers/operations/${OPERATION_ID}?api-version=2025-06-01")
  PURCHASE_STATUS=$(printf '%s' "$OP_RESULT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' 2>/dev/null || true)
  [[ "$PURCHASE_STATUS" == "succeeded" || "$PURCHASE_STATUS" == "failed" ]] && break
  sleep 5
done

if [[ "$PURCHASE_STATUS" == "succeeded" ]]; then
  # Belt-and-suspenders: confirm the number is actually in the account's owned list, not just that the
  # operation reported success -- matches the same discipline as Stage 7's NoAutoUpgrade verification
  # (don't trust an API's own success signal alone when a cheap direct check is available).
  OWNED=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
    "https://${ACS_NAME}.canada.communication.azure.com/phoneNumbers?api-version=2025-06-01")
  if printf '%s' "$OWNED" | grep -qF "$CANDIDATE_NUMBER"; then
    ok "purchased and confirmed owned: $CANDIDATE_NUMBER"
    write_env "PHONE_NUMBER" "$CANDIDATE_NUMBER"
  else
    err "operation reported succeeded but $CANDIDATE_NUMBER isn't in the owned-numbers list."
    err "Do not treat this as purchased. Check the Azure portal manually before re-running this stage."
    exit 1
  fi
elif [[ "$PURCHASE_STATUS" == "failed" ]]; then
  # R-09 in practice: the reserved number can be gone by purchase time. Per Marco's explicit
  # instruction -- never silently substitute a different number than the one approved. Auto-run ONE
  # fresh search so the next attempt has a real candidate ready, print it, then STOP and wait; do not
  # loop, do not auto-purchase the replacement.
  err "Purchase FAILED. Operation result:"
  printf '%s\n' "$OP_RESULT" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$OP_RESULT"
  warn "The number searched above ($CANDIDATE_NUMBER) is not purchased. Nothing was bought, no"
  warn "half-completed state -- write_env for PHONE_NUMBER was never called."
  say "Running a fresh search for area code $AREA_CODE so you have a live candidate to review:"
  RETRY_SEARCH=$(curl -s -X POST -H "Authorization: Bearer $ACS_TOKEN" -H "Content-Type: application/json" \
    "https://${ACS_NAME}.canada.communication.azure.com/availablePhoneNumbers/countries/CA/:search?api-version=2025-06-01" \
    -d "{\"phoneNumberType\":\"geographic\",\"assignmentType\":\"application\",\"capabilities\":{\"calling\":\"inbound\",\"sms\":\"none\"},\"areaCode\":\"$AREA_CODE\",\"quantity\":1}")
  printf '%s\n' "$RETRY_SEARCH" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$RETRY_SEARCH"
  err "STOP — this is a new candidate, not yet approved. Review it with Marco, then re-run this stage"
  err "(everything through Stage 8 is idempotent) rather than proceeding automatically."
  exit 1
else
  err "purchase operation still '$PURCHASE_STATUS' after ~90s — not resolved within this script's poll"
  err "window. Do not assume success or failure. Check manually:"
  err "  curl -H \"Authorization: Bearer \$TOKEN\" \"https://${ACS_NAME}.canada.communication.azure.com/phoneNumbers/operations/${OPERATION_ID}?api-version=2025-06-01\""
  exit 1
fi
fi

# ── Stage 10: write ADR-001 and ADR-002 ──────────────────────────────────────
stage "Write ADR-001 (data residency) and ADR-002 (geography knobs)"

# Guarded 2026-08-21. Originally deferred as low-risk ("nothing exists yet to clobber") -- that
# stopped being true the moment these files were first written, and a later re-run proved it: the
# heredoc below regenerated both ADRs with that run's own live values, which regressed a committed
# fact (the purchased number, `+17059100383`) back to a template placeholder (`<pending>`) in
# ADR-002. Full diff: docs/phase0/findings.md. Skip once both files exist -- edit docs/adr/ directly
# from then on, never via this script.
if [[ -f "$ADR_DIR/ADR-001-data-residency.md" && -f "$ADR_DIR/ADR-002-geography-knobs.md" ]]; then
  ok "$ADR_DIR/ADR-001-data-residency.md and ADR-002-geography-knobs.md already exist, skipping regeneration -- edit them directly, never via this script"
else
say "docs/PLAN.md step 9: write these now, using R-05/R-06 findings just measured, not deferred."
mkdir -p "$ADR_DIR"

R06_ERROR_BLOCK='ERROR: (InvalidResourceProperties) The specified SKU '"'"'DataZoneStandard'"'"' of account deployment is not supported by the model '"'"'gpt-realtime-mini'"'"' version: '"'"'2025-10-06'"'"'.
Code: InvalidResourceProperties
Message: The specified SKU '"'"'DataZoneStandard'"'"' of account deployment is not supported by the model '"'"'gpt-realtime-mini'"'"' version: '"'"'2025-10-06'"'"'.'

R06_LINE=$([[ "${R06_ANSWER_SHORT:-}" == "OFFERED" ]] || [[ "$DATAZONE_OK" == "1" ]] \
  && echo "**R-06 result: DataZoneStandard IS offered for this model/region as of $(date -u +%Y-%m-%d) — this contradicts the block below and needs Marco's review before this ADR is treated as settled.**" \
  || echo "**R-06 result: DataZoneStandard is confirmed NOT offered for \`${DEPLOYMENT_NAME:-gpt-realtime-mini}\` version \`${MODEL_VERSION:-2025-10-06}\`, as of $(date -u +%Y-%m-%d) — an empirical deployment attempt, not an assumption.** Exact error returned by the account-deployment PUT call against \`${AOAI_NAME:-<aoai resource>}\`:

\`\`\`
$R06_ERROR_BLOCK
\`\`\`

Explicit and unambiguous — a SKU-not-supported error for this model+version, not a quota or permission
error that might resolve differently under other conditions.")

cat > "$ADR_DIR/ADR-001-data-residency.md" <<EOF
# ADR-001 — Data residency

Status: Accepted
Date: $(date -u +%Y-%m-%d)

## Context

$R06_LINE

Full record: \`docs/phase0/findings.md\`, "R-06 — DataZoneStandard deployment probe".

## Decision

Every resource this project provisions (ACS, Azure OpenAI, Container Apps, Table Storage) is created in
a single Canadian jurisdiction (Canada Central / \`dataLocation: Canada\`). Data **at rest** stays in
that geography.

Quotable, from the Foundry data-privacy page:

> For any deployment type labeled 'Global,' prompts and responses may be processed in any geography
> where the relevant model sold by Azure is deployed. [...] any data stored at rest [...] is stored in
> the customer-designated geography. Only the location of processing is affected.

**This project's resource footprint is entirely Canadian, but that does not make its processing
Canadian-only — the two claims are separate and neither should be conflated with the other.** The
\`${DEPLOYMENT_NAME:-gpt-realtime-mini}\` deployment used here is \`GlobalStandard\`, the only SKU R-06
confirmed is actually offered for this model. Global deployment type means inference may run in any of
the six Global Standard regions (canadacentral, centralus, eastus2, francecentral, swedencentral,
southindia) — spanning the US, EU, and India, not just Canada — regardless of where the resource itself
is deployed. A real Canadian bank under strict data-residency requirements would need a Standard
(single-region) deployment type instead of Global to close that gap — Data Zone is not available as that
alternative for this model, per R-06 above.

## Consequences

- At-rest data (ACS call artifacts, Table Storage, App Insights) is provably single-jurisdiction
  Canadian — this claim is fully supported and should be stated without hedging.
- Processing (the realtime model call itself) is not single-jurisdiction — this is disclosed, not
  hidden, and should never be stated as "processed only in Canada" anywhere in this project's docs or
  portfolio write-up. That would overstate the residency guarantee this architecture actually provides.
- Retention figures: do not cite a "30 days" abuse-monitoring retention figure anywhere in this
  project's documentation — it does not appear in current Microsoft documentation as of the scoping pass
  that produced \`docs/PLAN.md\`, and using it would be citing a number nobody re-confirmed. Cite the DPA
  directly, or state that retention is not independently verified, rather than repeating an unconfirmed
  figure.
EOF
ok "wrote $ADR_DIR/ADR-001-data-residency.md"

cat > "$ADR_DIR/ADR-002-geography-knobs.md" <<EOF
# ADR-002 — Geography knobs

Status: Accepted
Date: $(date -u +%Y-%m-%d)

## Context

The question this ADR originally set out to answer: does ACS's \`dataLocation\` property constrain which
countries or localities a phone number can be purchased from, forcing this project's ACS resource and
Azure OpenAI resource into a coordinated regional split? **Answer, confirmed empirically: no.** Number
purchase is gated only by the Azure subscription's billing address (Canada), never by the ACS resource's
\`dataLocation\` — there was never a technical coupling to design around. \`location\` (ACS's ARM
control-plane field) is always \`'global'\` — ACS is not a regional resource — and is independent of
\`dataLocation\` (data-at-rest geography, governing only call artifacts and resource metadata).

That question turned out not to be the interesting one. Investigating it surfaced a real, undocumented
platform constraint instead:

**ACS's Canadian geographic phone number inventory is thin and volatile, not merely uncoupled from
\`dataLocation\`.** Measured, not assumed — full queries and evidence in \`docs/phase0/findings.md\`
("R-05", "R-05 supplemental", "ACS Canadian phone number inventory is genuinely volatile"):

- An unfiltered List Available Localities query (no \`locality\`/\`administrativeDivision\` filter — the
  only way to see the whole inventory rather than test one guess at a time) returned **10 localities in
  the entire country** at first check: Brockville, Guelph, North Bay, Sault Sainte Marie, Thunder Bay
  (all ON); Chicoutimi, Montreal, Thetford Mines (QC); Biggar, Lanigan (SK).
- **Toronto is absent. No GTA-adjacent locality is present at all** — none of 416/647/437/905/289 are
  reachable through this API, at any point this project queried it. Confirmed against the country-wide,
  unfiltered list, not inferred from a single Toronto-filtered query returning \`404\` — a control query
  against a locality that *is* listed (Guelph) returned a clean \`200\` with a real area code in the same
  window, ruling out a broken endpoint, a bad token, or a malformed request as the explanation.
- **The inventory changed within the same session, ~20 minutes apart.** Guelph returned \`200\` /
  \`areaCode: 226\` on first check. A re-check roughly 20 minutes later returned \`404 NotFound\`,
  reproduced three times, two seconds apart, to rule out a transient blip. A re-run of the unfiltered
  nationwide dump confirmed the drop was real inventory change, not a query fluke: 8 localities
  remained — Guelph and Biggar both gone, the other 8 unchanged.
- No documented explanation from Microsoft rules this in or out — not a rate limit, not a permissions
  scope, not an API version issue (all independently ruled out; see \`findings.md\`). The most plausible
  explanation is real-time contention for a small shared number pool across every ACS customer
  purchasing in the same localities, but that is stated there as inference, not as a confirmed fact.

## Decision

Two decisions follow directly from this finding, not from the original \`dataLocation\` question:

1. **Decision 13 (\`docs/PLAN.md\`) revised.** "Canada local geographic, Toronto area
   (416/647/437/905/289)" is unfulfillable against ACS's actual Canadian inventory — not "available but
   taken," genuinely absent. Revised to **705 (North Bay / Sault Ste Marie, ON)**, live-confirmed
   purchasable via Search Available Phone Numbers immediately before purchase, not carried over from an
   earlier List Area Codes check in the same session.
2. **R-09 added** to \`docs/PLAN.md\`'s tracked risks and to \`CLAUDE.md\`'s stop conditions: the
   purchased number is never released, by any script, at any phase, for any reason. Given observed
   volatility, there is no guarantee an equivalent replacement — or any number in the same numbering
   plan area — would still be purchasable if this one were ever lost, unlike almost every other resource
   in this project, which Bicep/the deploy CLI can recreate identically. Every purchase-adjacent script
   must re-verify actual inventory via Search Available Phone Numbers (not List Area Codes / List
   Localities, which only prove a locality is server-side recognized, not that a number is currently
   reservable) immediately before acting — never from an earlier-in-session check, however recent.

Number actually purchased under this revised decision: \`${PHONE_NUMBER:-<pending>}\` (\`COSTS.md\`,
"First billable resource purchased").

## Consequences

- The \`dataLocation\`/number-purchase coupling question is fully closed: no cross-region hop, no design
  constraint to build around. ACS (\`location: global\`, \`dataLocation: Canada\`) and Azure OpenAI
  (Canada Central) share a single jurisdiction by choice, not by technical requirement — the residual
  gap in that jurisdiction claim is ADR-001's, not this one's.
- The real constraint this project designed around here is inventory scarcity and volatility, not
  geography-pairing. There is no further number-purchase code path planned past Phase 0, but if one is
  ever added, it must treat a \`200\` from the locality/area-code list endpoints as a point-in-time
  snapshot with no stated TTL, never a purchase guarantee.
- This is a genuinely undocumented characteristic of ACS's Canadian geographic-number product — not
  inferable from Microsoft's public pricing or availability pages, not something a plan written from
  documentation alone would have caught. Recorded here as a platform finding for the Phase 8 portfolio
  write-up: the kind of thing that distinguishes having built on ACS from having read about it, not a
  note explaining away a changed plan.
EOF
ok "wrote $ADR_DIR/ADR-002-geography-knobs.md"
fi
note "Both ADRs use the R-06 result and the R-05 inventory finding measured earlier this run. Read them"
note "before committing — the DataZone error block and the purchased number are templated from this"
note "run's actual results, not assumed."

# ── Stage 11: verify the echo WebSocket app is present and reviewed ──────────
stage "Verify the echo WebSocket app (docs/echo-app/) is present and git-tracked"
say "This stage no longer generates the echo app from a frozen template. The real, human-reviewed"
say "app lives in docs/echo-app/ -- fixed and signed off 2026-08-21 (commit 1004d54): correct SDK"
say "version (1.4.0, not the broken 1.2.* this script used to template), B2 DTMF-value gating, and a"
say "build-time pip-freeze assertion. This stage only verifies that file is where it should be."

# Anchored to the git repo root via `git rev-parse`, not a relative "$SCRIPT_DIR/../..." chain --
# that class of path is exactly what caused the ECHO_DIR misdirection this project already shipped
# once: an untracked, unreviewed echo app (unconditional raw-DTMF logging, no B2 gating, the broken
# 1.2.* SDK pin) got silently built and nearly deployed, caught only because an unrelated arch
# mismatch failed first -- not by any guard. Full account: docs/phase0/findings.md, "Stage 12 --
# ECHO_DIR misdirection". A path built by counting ".." is correctness verified by eye; a path built
# from `git rev-parse --show-toplevel` is correctness verified by the tool.
REPO_TOPLEVEL="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel)" || {
  err "could not resolve the git repo root from $SCRIPT_DIR -- refusing to guess where the echo app lives"
  on_error 1
}
ECHO_DIR="$REPO_TOPLEVEL/Azure-Banking-Voice-Agentic-AI/docs/echo-app"

# Hard assertion, not a soft check: ECHO_DIR must exist AND be git-tracked, or the script stops here.
# This is the guard that would have caught the ECHO_DIR misdirection the moment it happened, instead
# of silently building whatever sat at the wrong path. There is deliberately no "generate it if
# missing" fallback left in this script -- a wrong path must stop the script, never regenerate from a
# template.
if [[ ! -f "$ECHO_DIR/app.py" ]]; then
  err "ECHO_DIR=$ECHO_DIR has no app.py. Either this path is wrong or the file was moved/deleted --"
  err "either way, refusing to proceed without it. Fix docs/echo-app/ directly, never via this script."
  on_error 1
fi
if ! git -C "$ECHO_DIR" ls-files --error-unmatch app.py requirements.txt Dockerfile >/dev/null 2>&1; then
  err "ECHO_DIR=$ECHO_DIR/{app.py,requirements.txt,Dockerfile} exist but aren't all git-tracked --"
  err "refusing to build from an unreviewed file. This is exactly the failure mode that nearly shipped"
  err "an unreviewed, B2-shaped image before (docs/phase0/findings.md, 'Stage 12 -- ECHO_DIR misdirection')."
  on_error 1
fi
ok "$ECHO_DIR verified: app.py/requirements.txt/Dockerfile present and git-tracked"

# ── Stage 12: build, push (Docker Hub, not ACR), and deploy ──────────────────
stage "Build, push, and deploy the echo app to Container Apps"
say "Avoiding az containerapp up's auto-provisioned ACR (~\$5/mo, not in docs/PLAN.md's budget)."
say "Pushing to Docker Hub's free tier instead, then pointing Container Apps at that external image."

ask DOCKERHUB_USERNAME "Docker Hub username:"
ask_secret DOCKERHUB_TOKEN "Docker Hub access token, Read & Write scope (Account Settings → Security → New Access Token; set the Access permissions dropdown to Read & Write — this same token both pushes the image below and is used as the Container App's pull credential later, so it needs both; do NOT grant Delete, which neither step uses):"
write_env "DOCKERHUB_USERNAME" "$DOCKERHUB_USERNAME"

IMAGE="docker.io/${DOCKERHUB_USERNAME}/azbank-echo-p0:latest"
LOGIN_OUTPUT="$(echo "$DOCKERHUB_TOKEN" | docker login docker.io -u "$DOCKERHUB_USERNAME" --password-stdin 2>&1)" || {
  err "docker login to docker.io failed for user '$DOCKERHUB_USERNAME' -- most likely the token is"
  err "wrong, expired, or doesn't have Read & Write scope (Account Settings → Security → the token's"
  err "Access permissions dropdown). Generate a fresh Read & Write token and re-run this script --"
  err "the username/token prompt above will ask again."
  err "Raw docker login output:"
  sed 's/^/    /' <<<"$LOGIN_OUTPUT"
  on_error 1
}
ok "logged in to docker.io as $DOCKERHUB_USERNAME"

# `docker buildx build --platform linux/amd64`, not plain `docker build`: a classic-builder build on
# Apple Silicon defaults to arm64, which Container Apps rejects at `containerapp create` --
# "no child with platform linux/amd64 in index ...". Found live 2026-08-21 (docs/phase0/findings.md,
# "Stage 12 -- ECHO_DIR misdirection"). buildx build+push in one step also avoids a separate
# build-then-push manifest-shape mismatch.
#
# --provenance=false --sbom=false: buildx attaches a provenance/SBOM attestation manifest to the
# index by default, tagged Platform: unknown/unknown alongside the real linux/amd64 one. The original
# failure here was Azure walking an image index looking for a platform child and not finding one --
# Azure's resolver has never been shown to handle an index with an unknown/unknown entry cleanly, and
# the one time it walked an index at all, it failed. Eliminating the variable is free; testing whether
# Azure tolerates it costs a billable `containerapp create`. Verified manually 2026-08-21: with these
# flags, `docker buildx imagetools inspect` shows a single linux/amd64 manifest, no second entry.
docker buildx build --platform linux/amd64 --provenance=false --sbom=false -t "$IMAGE" --push "$ECHO_DIR"
ok "built for linux/amd64 and pushed $IMAGE"

# Fail loudly here, before any Azure spend, if the pushed image isn't actually linux/amd64 --
# Container Apps only rejects a mismatched image at `containerapp create`, after ARM has already
# accepted the request. Same shape as the Dockerfile's own `pip freeze && test -s` build assertion:
# verify before the billable step, not after.
#
# Queries the platform field structurally (`--format`), not by grepping `imagetools inspect`'s
# display text. Verified empirically 2026-08-21: with --provenance=false --sbom=false, the pushed
# image is a flat (non-index) manifest, and a flat manifest's default `imagetools inspect` output
# never prints a "Platform:" line at all -- `grep -q "linux/amd64"` against it returns exit 1 even
# for a correctly-built linux/amd64 image. That version of this gate would have failed closed, but
# for the wrong reason, on every future correct build -- a gate that fails (or passes) for the wrong
# reason is worse than no gate, so it's replaced rather than patched around.
BUILT_PLATFORM="$(docker buildx imagetools inspect "$IMAGE" --format '{{.Image.Platform.OS}}/{{.Image.Platform.Architecture}}' 2>&1)" || {
  err "docker buildx imagetools inspect failed against $IMAGE -- can't confirm what actually got pushed"
  err "$BUILT_PLATFORM"
  on_error 1
}
if [[ "$BUILT_PLATFORM" != "linux/amd64" ]]; then
  err "pushed image $IMAGE is platform '$BUILT_PLATFORM', not linux/amd64 -- Container Apps will reject it."
  on_error 1
fi
ok "confirmed $IMAGE is linux/amd64 (queried structurally, not grepped from display text)"

note "The image itself has no secrets baked in — ACS_CONNECTION_STRING and APP_BASE_URL are runtime"
note "env vars set on the Container App below, never build args or COPY'd files, so docker history"
note "on this image reveals nothing. Visibility is still worth setting explicitly: docker push can't"
note "set it, and Docker Hub's auto-create default isn't something this wizard should assume."
open_url "https://hub.docker.com/repository/docker/${DOCKERHUB_USERNAME}/azbank-echo-p0/settings"
step "Set visibility to Private (free tier includes 1 private repo)."
confirm "Confirmed the repo is set to Private?" \
  || warn "left as whatever Docker Hub defaulted to — not a credential leak (see above), but there's no reason to publish this project's internal call-handling code by accident."

ACS_CONNECTION_STRING=$(az communication list-key --name "$ACS_NAME" --resource-group "$RESOURCE_GROUP" --query primaryConnectionString -o tsv)

if az containerapp env show --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  ok "Container Apps environment $CAE_NAME already exists"
else
  az containerapp env create --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --location "$LOCATION" --output none
  ok "Container Apps environment $CAE_NAME created"
fi

# Computed BEFORE create, not queried after: verified live 2026-08-21 that a Container App's FQDN is
# fully deterministic from {app-name}.{environment's own defaultDomain}, and the environment already
# exists by this point -- so the real APP_BASE_URL is knowable up front. This replaces a
# create-with-a-placeholder-secret-then-patch-it-after design that shipped a container whose running
# process started with APP_BASE_URL="placeholder" and never picked up the later fix: Container Apps
# injects secretRef env vars as literal OS env vars at container start, not a live-refreshed value,
# and no new revision was ever created by the later `secret set`/`update` calls (confirmed: exactly
# one revision existed, from container start to failure). CALLBACK_URL built from "placeholder" is
# exactly why ACS rejected answer_call() with "The field CallbackUri is invalid." Full account:
# docs/phase0/findings.md, "APP_BASE_URL placeholder race".
ENV_DEFAULT_DOMAIN=$(az containerapp env show --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --query "properties.defaultDomain" -o tsv)
APP_BASE_URL="https://${CONTAINERAPP_NAME}.${ENV_DEFAULT_DOMAIN}"

if az containerapp show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  # `az containerapp update --image` alone does two things wrong on a retry: (1) it takes no --secrets
  # flag at all, so an already-existing app keeps whatever secret value it already has -- for this
  # project's currently-deployed app, that's the stale "placeholder" app-base-url from the race
  # documented above; (2) --image is a mutable Docker Hub `:latest` tag, so if the tag string is
  # byte-identical to what's already on the app, Azure may see no spec diff and skip creating a new
  # revision at all -- meaning secretRef env vars, which are only read at container start, would never
  # be re-read even if the secret's stored value were corrected first. Fixed by (1) setting secrets
  # explicitly via the separate `secret set` verb before updating, and (2) forcing a distinct revision
  # unconditionally via --revision-suffix, so a new container start (and therefore a fresh env-var
  # read) happens regardless of whether Azure would have detected an image-string diff on its own.
  say "updating existing container app: refreshing secrets, then forcing a new revision"
  az containerapp secret set \
    --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" \
    --secrets "acs-conn=$ACS_CONNECTION_STRING" "app-base-url=$APP_BASE_URL" \
    --output none
  az containerapp update \
    --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" \
    --image "$IMAGE" \
    --revision-suffix "p0$(date -u +%Y%m%d%H%M%S)" \
    --output none
  ok "container app $CONTAINERAPP_NAME updated: secrets refreshed, new revision forced"
else
  az containerapp create \
    --name "$CONTAINERAPP_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --environment "$CAE_NAME" \
    --image "$IMAGE" \
    --registry-server docker.io \
    --registry-username "$DOCKERHUB_USERNAME" \
    --registry-password "$DOCKERHUB_TOKEN" \
    --target-port 8000 \
    --ingress external \
    --min-replicas 1 --max-replicas 1 \
    --cpu 0.25 --memory 0.5Gi \
    --env-vars "ACS_CONNECTION_STRING=secretref:acs-conn" "APP_BASE_URL=secretref:app-base-url" \
    --secrets "acs-conn=$ACS_CONNECTION_STRING" "app-base-url=$APP_BASE_URL" \
    --output none
  ok "container app $CONTAINERAPP_NAME created (min-replicas=1, 0.25 vCPU / 0.5 GiB per docs/PLAN.md)"
fi

# Sanity check, not blind trust in the formula above: confirm Azure actually assigned what was
# computed, before Event Grid gets wired to a possibly-wrong URL and before healthz is even checked.
APP_FQDN=$(az containerapp show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" --query "properties.configuration.ingress.fqdn" -o tsv)
if [[ "https://$APP_FQDN" != "$APP_BASE_URL" ]]; then
  err "computed APP_BASE_URL ($APP_BASE_URL) doesn't match the live FQDN (https://$APP_FQDN) -- the"
  err "defaultDomain assumption this fix relies on may not hold here. Investigate before proceeding."
  on_error 1
fi
ok "confirmed APP_BASE_URL was correct from container start: $APP_BASE_URL"

# Diagnostic setting, explicit: found live 2026-08-21 that the environment's built-in
# appLogsConfiguration (auto-wired to a Log Analytics workspace at `containerapp env create` time)
# was NOT actually delivering console logs to that workspace's ContainerAppConsoleLogs table --
# confirmed empty after over an hour of a running, logging container. `az containerapp logs show`'s
# own streaming buffer also doesn't retain back to container start, so a boot-time issue is currently
# unrecoverable once the buffer scrolls past it. This adds the classic Diagnostic Settings resource
# as a second, standard path to the same workspace -- whether it resolves the gap or the native path
# was simply slow, confirm after this redeploy, don't assume either way. Full account:
# docs/phase0/findings.md, "Log Analytics: two workspaces, neither delivering".
CAE_ID=$(az containerapp env show --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --query id -o tsv)
LOGS_WORKSPACE_ID=$(az containerapp env show --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --query "properties.appLogsConfiguration.logAnalyticsConfiguration.customerId" -o tsv)
LOGS_WORKSPACE_RESOURCE_ID=$(az monitor log-analytics workspace list --resource-group "$RESOURCE_GROUP" --query "[?customerId=='${LOGS_WORKSPACE_ID}'].id | [0]" -o tsv)
if [[ -z "$LOGS_WORKSPACE_RESOURCE_ID" ]]; then
  warn "couldn't resolve the environment's linked workspace to a resource ID -- skipping the explicit"
  warn "diagnostic setting this run. Console logs still flow through the native appLogsConfiguration"
  warn "path (unconfirmed whether it's actually delivering -- see findings.md)."
else
  az monitor diagnostic-settings create \
    --name "azbank-p0-console-logs" \
    --resource "$CAE_ID" \
    --workspace "$LOGS_WORKSPACE_RESOURCE_ID" \
    --logs '[{"category":"ContainerAppConsoleLogs","enabled":true},{"category":"ContainerAppSystemLogs","enabled":true}]' \
    --output none
  ok "diagnostic setting wired: environment console+system logs -> $LOGS_WORKSPACE_RESOURCE_ID"
fi

write_env "APP_BASE_URL" "$APP_BASE_URL"
ok "app live at $APP_BASE_URL"

say "Waiting for the container to actually answer /healthz before wiring Event Grid to it. This"
say "matters because a wrong SDK parameter name (one of the VERIFY items in this script's header)"
say "would crash-loop the container WITHOUT 'az containerapp create' itself failing — ARM considers"
say "the resource created successfully even if the process inside it dies on import. Catching that"
say "here, loudly, beats discovering it as a cryptic Event Grid validation-handshake failure next."
HEALTHY=0
for _ in $(seq 1 12); do
  if curl -sf "${APP_BASE_URL}/healthz" >/dev/null 2>&1; then HEALTHY=1; break; fi
  sleep 10
done
if [[ "$HEALTHY" != "1" ]]; then
  err "container never answered /healthz after 2 minutes — it's very likely crash-looping."
  err "Recent logs (check the three VERIFY items at the top of this script first):"
  az containerapp logs show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" --type console --tail 50 2>/dev/null | sed 's/^/    /' || true
  on_error 1
fi
ok "container is healthy (/healthz responding) — safe to wire Event Grid to it"

# PROVISION_TIME is NOT written here anymore. Found live 2026-08-21: a healthy /healthz response
# proves the container is up, not that it can answer a real call -- this app was healthy for over
# an hour while every real call to it failed. R-04's window now opens in 02-test-calls.sh instead,
# gated on a confirmed Microsoft.Communication.CallConnected event in the Container App logs, not
# on this script reaching this line. Full account: docs/phase0/findings.md,
# "healthz-as-window-gate -- the design flaw, more interesting than the bug that triggered it".
note "R-04's 72h window does NOT open here. Run 02-test-calls.sh next -- it only writes PROVISION_TIME"
note "once a real call is confirmed answered (a CallConnected event in the logs), not on healthz alone."

say "Wiring the Event Grid subscription so ACS's IncomingCall event reaches the app."
az eventgrid event-subscription create \
  --name "azbank-p0-incoming-call" \
  --source-resource-id "$(az communication show --name "$ACS_NAME" --resource-group "$RESOURCE_GROUP" --query id -o tsv)" \
  --endpoint "${APP_BASE_URL}/api/incoming-call" \
  --endpoint-type webhook \
  --included-event-types "Microsoft.Communication.IncomingCall" \
  --output none
ok "Event Grid subscription wired"

finish

printf '\n%sNext:%s run %s02-test-calls.sh%s today — dial the number 3 times. R-04'"'"'s 72h window has NOT\n' \
  "$BOLD" "$RESET" "$BLUE" "$RESET"
printf 'started yet; it opens inside that script, only once a call is confirmed answered.\n\n'
