#!/usr/bin/env bash
#
# Phase 0 wizard, script 1 of 4 — Provisioning.
# Generated by the /wizard skill for Azure-Banking-Voice-Agentic-AI.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit it.
#
# WHY FOUR SCRIPTS, NOT ONE
#   Phase 0 (docs/PLAN.md) spans real-world waits a single sitting can't absorb: 3 test calls today,
#   then a 24h wait for Cost Analysis to populate, then a 72h idle-billing observation window before
#   teardown. Four scripts, run on their own days, handing state forward via a shared .env.phase0:
#     01-provision.sh          (today)      — this script. Pre-checks, the hard gate, all provisioning.
#     02-test-calls.sh         (today, after 01) — 3 real calls from your mobile; measures the meters.
#     03-cost-check-24h.sh     (tomorrow)   — reads real Cost Analysis, sanity-checks against estimate.
#     04-teardown-and-r08.sh   (+72h from provisioning) — idle billing verdict, R-08, ADRs, teardown.
#
# WHAT THIS SCRIPT AUTOMATES vs WHAT ONLY YOU CAN DO
#   Everything in this script is Azure CLI / REST calls this wizard runs FOR you — confirmed at each
#   state-changing step. The only things only you can do live in 02-test-calls.sh (dialing a real phone)
#   and in the elapsed-time waits between scripts 1→3→4. This script provisions and then stops; it does
#   not dial anything.
#
# HARD GATE — restated verbatim from CLAUDE.md, because CLAUDE.md requires that:
#   "No billable Azure resource is created without Marco typing `APPROVED: <phase name>`... Never
#   auto-accept a diff that provisions a billable resource... no exceptions, no partial provisioning
#   ahead of it."
#   Stages before the gate below are read-only (provider status, Models API). Nothing that creates,
#   modifies, or spends is called before you type the exact string `APPROVED: Phase 0`.
#
# KNOWN VERIFICATION ITEMS — flagged instead of guessed, per this project's own "verify, don't assume"
# rule (R-01 already burned it once on an unverified regional claim). Each is marked VERIFY inline too:
#   1. Models API `api-version` for the deprecationDate query (stage 2) — confirm the version this
#      wizard uses still returns a 200; if not, check the AI Foundry portal's Models page instead.
#   2. List Area Codes REST path/api-version (stage 8) — Communication Services phone number APIs move
#      fast; confirm against the current Azure REST API reference before running that stage.
#   3. The exact `azure-communication-callautomation` SDK parameter/enum names in the generated echo app
#      (stage 11) — written against the shapes documented in docs/PLAN.md's "Architecture" section
#      (verified), but the SDK's Python class/enum names for MediaStreamingOptions were not independently
#      re-verified for this wizard. Check them against the installed package version's docs before
#      building the container image.
#
# COST NOTE NOT IN docs/PLAN.md's BUDGET TABLE: `az containerapp up --source` auto-provisions a Basic
# Azure Container Registry (~$5/mo) if you let it pick a registry. That is real, unbudgeted fixed cost
# against the $25 ceiling. This script avoids it — it builds locally and pushes to Docker Hub's free
# tier instead, and points Container Apps at that external image. Flagged here because it's the kind of
# thing that's easy to wave through without noticing it changed the budget.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
_STAGE_INDEX=0
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/.env.phase0}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  This wizard runs Azure CLI/REST calls on your behalf and confirms before anything\n' "$DIM"
  printf '  billable happens. Stop any time with Ctrl-C and re-run later — it remembers values\n'
  printf '  already saved in %s.%s\n' "$ENV_FILE" "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
err()  { printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET"; }
ok()   { printf '  %s✓ %s%s\n' "$GREEN" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# require_gate — the CLAUDE.md hard gate. Blocks until the human types the exact phrase.
require_gate() {
  local phrase="$1" reply=""
  printf '\n'
  warn "HARD GATE — nothing past this point is free. Everything below creates or spends against"
  warn "the \$25/month ceiling. This is the stop CLAUDE.md requires before any billable resource."
  printf '\n'
  while true; do
    printf '  %sType exactly (case-sensitive):%s %s%s%s\n  > ' "$BOLD" "$RESET" "$BOLD" "$phrase" "$RESET"
    read -r reply || true
    if [[ "$reply" == "$phrase" ]]; then
      ok "gate passed — proceeding"
      return 0
    fi
    err "that didn't match \"$phrase\" exactly. Ctrl-C to stop, or try again."
  done
}

finish() {
  _clear
  printf '\n%s%s  ✓ Script complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# Fixed identifiers for this project. Change here if you want different names before running —
# not something worth a prompt each run.
SUBSCRIPTION_ID="960936b9-ecde-465b-be8d-776ca077dcd0"
LOCATION="canadacentral"
RESOURCE_GROUP="rg-azure-banking-voice-agentic-ai"
AOAI_NAME="aoai-azure-banking-voice-cc"
ACS_NAME="acs-azure-banking-voice"
CAE_NAME="cae-azure-banking-voice-p0"
CONTAINERAPP_NAME="ca-azbank-echo-p0"
MODEL_NAME="gpt-realtime-mini"
MODEL_VERSION="2025-10-06"          # the GA version this project pins to (decision 14, revised
                                     # 2026-08-20 from 2025-12-15/isDefaultVersion after the live
                                     # Models API pull showed 2025-10-06 has ~3.7 more months of
                                     # runway at identical audio-token pricing — see PLAN.md decision 14
MODEL_VERSION_OLD="2025-12-15"      # the isDefaultVersion — retires 2026-12-15, ~4mo out; not pinned
DEPLOYMENT_NAME="gpt-realtime-mini" # deployment name == model name, matching B3's allowlist string

REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"   # docs/phase0/wizard -> project root
FINDINGS_FILE="$SCRIPT_DIR/../findings.md"
ADR_DIR="$REPO_ROOT/docs/adr"

# on_error — fires on any unexpected command failure (set -e / ERR trap), and is also called
# explicitly by the post-deploy health check below. Reports exactly what exists in $RESOURCE_GROUP
# at the moment of failure, and offers to delete the Container App/environment right then if either
# made it into existence — the two resources that actually bill per-hour, as opposed to the ACS
# resource, AOAI resource+deployment, and phone number, which are either free to hold idle or
# deliberately kept (the number). Exists because a script that dies mid-provisioning with no cleanup
# path is exactly how "no billable resource without approval" quietly becomes "one nobody's watching".
on_error() {
  local exit_code="${1:-$?}"
  _clear
  printf '\n%s%s  ✗ 01-provision.sh failed at stage %s/%s (exit %s)%s\n\n' \
    "$BOLD" "$RED" "$_STAGE_INDEX" "$TOTAL_STAGES" "$exit_code" "$RESET"
  say "Resources that exist in $RESOURCE_GROUP right now:"
  az resource list --resource-group "$RESOURCE_GROUP" --output table 2>/dev/null \
    || note "(resource group itself doesn't exist yet, or the query failed — nothing billable then)"
  printf '\n'
  note "Only two things here bill per-hour: a Container App (min-replicas=1) and its environment."
  note "Everything else (resource group, ACS resource, AOAI resource+deployment, the phone number)"
  note "is either free to hold idle or deliberately kept — leaving those is not a problem."
  if az containerapp show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
    warn "Container App $CONTAINERAPP_NAME exists and is billing right now."
    if confirm "Delete it now? (safe — fix the cause and re-run this script from the top afterward)"; then
      az containerapp delete --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" --yes --output none 2>/dev/null || true
      az containerapp env delete --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --yes --output none 2>/dev/null || true
      ok "deleted — re-run 01-provision.sh from the top once you've fixed the cause above"
    else
      warn "left running — it is billing until you delete it or re-run this script to completion."
    fi
  else
    ok "no Container App exists yet — nothing here is billing beyond the number (by design)"
  fi
  exit "$exit_code"
}
trap 'on_error $?' ERR

banner "Azure-Banking-Voice-Agentic-AI — Phase 0, script 1/4: Provisioning"

# ── Stage 1: pre-flight (free, read-only) ──────────────────────────────────
stage "Pre-flight checks (free, read-only)"
say "Confirming tools and the correct subscription before anything else."

for tool in az curl docker python3; do
  if ! command -v "$tool" >/dev/null 2>&1; then
    err "$tool not found on PATH — install it before continuing."
    exit 1
  fi
done
ok "az, curl, docker, python3 all present"

CURRENT_SUB=$(az account show --query id -o tsv 2>/dev/null || true)
if [[ "$CURRENT_SUB" != "$SUBSCRIPTION_ID" ]]; then
  warn "az is on subscription $CURRENT_SUB, expected $SUBSCRIPTION_ID"
  if confirm "Switch to it now (az account set)?"; then
    az account set --subscription "$SUBSCRIPTION_ID"
    ok "switched"
  else
    err "wrong subscription — stopping rather than provisioning in the wrong place."
    exit 1
  fi
else
  ok "az is on the correct subscription ($SUBSCRIPTION_ID)"
fi

SPENDING_LIMIT=$(az account show --query "spendingLimit" -o tsv 2>/dev/null || echo "unknown")
note "spendingLimit: $SPENDING_LIMIT — CLAUDE.md/PLAN.md record this as Off. Azure will not stop spend."
note "at any threshold; B4 (call-length/daily-cap) is the only brake. Confirm this still says Off."

REGISTRATION_STATE=$(az provider show --namespace Microsoft.Communication --query "registrationState" -o tsv 2>/dev/null || echo "NotRegistered")
note "Microsoft.Communication registration state: $REGISTRATION_STATE"

EXISTING_RG=$(az group exists --name "$RESOURCE_GROUP" 2>/dev/null || echo "false")
if [[ "$EXISTING_RG" == "true" ]]; then
  warn "resource group $RESOURCE_GROUP already exists — this wizard assumes a clean start."
  say "docs/handoffs/2026-08-19-scoping-complete-phase0-pending.md records the subscription as bare"
  say "(zero resource groups). If this is a re-run after a partial attempt, that's fine; if it's"
  say "unexpected, stop and find out what's in it before continuing."
  confirm "Continue anyway?" || exit 1
else
  ok "resource group $RESOURCE_GROUP does not exist yet — clean start confirmed"
fi

write_env "SUBSCRIPTION_ID" "$SUBSCRIPTION_ID"
write_env "RESOURCE_GROUP" "$RESOURCE_GROUP"
write_env "LOCATION" "$LOCATION"
write_env "CONTAINERAPP_NAME" "$CONTAINERAPP_NAME"
write_env "CAE_NAME" "$CAE_NAME"
# PROVISION_TIME is deliberately NOT written here. 04-teardown-and-r08.sh uses it to anchor R-04's
# 72h idle-billing observation window, and the Container App this measures doesn't exist until
# Stage 12 below -- writing it this early would understate the window by however long Stages 4-11
# take. Written at Stage 12 instead, right after the container passes its health check.

# ── Stage 2: R-01 — Models API deprecationDate check (free, read-only) ─────
stage "R-01 — verify gpt-realtime-mini retirement dates via the Models API"
say "Originally: docs/PLAN.md recorded this model listed TWICE with conflicting retirement dates per"
say "version (2025-10-06 as 2027-04-06 or 2026-09-21; 2025-12-15 as 2027-06-15 or 2026-12-15)."
say "Resolved 2026-08-20 by a live query: 2025-10-06 -> 2027-04-06, 2025-12-15 -> 2026-12-15 — the"
say "pessimistic case in both, confirmed real. Decision 14 was revised to pin 2025-10-06 on that"
say "basis (~3.7 more months of runway, identical cost). Re-querying now to reconfirm it still holds —"
say "dates on a live catalog can move, and this pin decision deserves the same live check every time"
say "this script runs, not just the one that found it."
warn "VERIFY: api-version below (2023-05-01) against the current Azure REST API reference before"
warn "trusting a non-200 response as \"not available\" rather than \"wrong api-version\"."

MODELS_JSON=$(az rest --method get \
  --url "https://management.azure.com/subscriptions/${SUBSCRIPTION_ID}/providers/Microsoft.CognitiveServices/locations/${LOCATION}/models?api-version=2023-05-01" \
  2>/dev/null || echo '{}')

R01_FINDING=$(python3 - "$MODELS_JSON" "$MODEL_NAME" <<'PYEOF'
import json, sys
data = json.loads(sys.argv[1] or "{}")
name = sys.argv[2]
rows = []
for m in data.get("value", []):
    model = m.get("model", {})
    if model.get("name") == name:
        rows.append({
            "version": model.get("version"),
            "deprecationDate": model.get("deprecation", {}) or model.get("lifecycleStatus"),
            "raw": model,
        })
print(json.dumps(rows, indent=2, default=str))
PYEOF
)
say "Matching entries for $MODEL_NAME in $LOCATION:"
printf '%s\n' "$R01_FINDING" | sed 's/^/    /'
if [[ "$R01_FINDING" == "[]" ]]; then
  warn "no rows matched — either the model isn't listed for $LOCATION, or the api-version needs updating."
  warn "Cross-check manually: AI Foundry portal → Models → filter to $LOCATION → $MODEL_NAME."
fi
{
  echo "## R-01 — Models API deprecation-date check"
  echo ""
  echo "Queried $(date -u +%Y-%m-%dT%H:%M:%SZ) against location=$LOCATION."
  echo '```json'
  printf '%s\n' "$R01_FINDING"
  echo '```'
  echo ""
} >> "$FINDINGS_FILE"
ok "recorded to $FINDINGS_FILE"
pause "Review the finding above, then press Enter to continue."

# ── Stage 3: THE HARD GATE ──────────────────────────────────────────────────
stage "HARD GATE — nothing billable happens without your explicit approval"
_clear
printf '\n%s%s  STOP CONDITIONS — restated verbatim from CLAUDE.md, per its own requirement%s\n\n' "$BOLD" "$RED" "$RESET"
cat <<'EOF'
  - No phase begins without written exit criteria from the prior phase and Marco's explicit approval.
  - No billable Azure resource is created without Marco typing `APPROVED: <phase name>`.
  - Never auto-accept a diff that provisions a billable resource, or that touches `dispatch/gate.py`
    (B1) or anything on the DTMF/PIN path (B2). These always get a human look before they land, no
    matter how mechanical the change appears.
  - `PROJECT_STATE.md` is updated before any session ends, and never exceeds its size ceiling.
  - Restate these conditions verbatim at the top of every session summary and after every `/compact`.
EOF
printf '\n'
say "Everything up to here (pre-flight, R-01 check) was read-only — zero dollars spent."
say "Everything from here on registers a provider, creates resources, purchases a phone number, and"
say "deploys compute. All of it is reversible except the number's ongoing \$1/mo (kept by design)."
require_gate "APPROVED: Phase 0"

# ── Stage 4: register Microsoft.Communication ───────────────────────────────
stage "Register Microsoft.Communication resource provider"
if [[ "$REGISTRATION_STATE" == "Registered" ]]; then
  ok "already registered"
else
  say "Registering (no cost — this is a subscription-level flag, not a resource)."
  az provider register --namespace Microsoft.Communication
  say "Polling until Registered (can take a couple of minutes)..."
  for _ in $(seq 1 30); do
    STATE=$(az provider show --namespace Microsoft.Communication --query registrationState -o tsv)
    [[ "$STATE" == "Registered" ]] && break
    sleep 10
  done
  if [[ "$STATE" == "Registered" ]]; then
    ok "Microsoft.Communication registered"
  else
    err "still $STATE after 5 minutes of polling — check az provider show manually before continuing."
    exit 1
  fi
fi

# ── Stage 5: resource group + Azure OpenAI resource ─────────────────────────
stage "Create resource group and the Azure OpenAI resource (Canada Central)"
say "Per decision 12 (docs/PLAN.md): Canada Central, no fallback. If this fails because realtime"
say "isn't servable here, STOP and report — do not let this wizard relocate the region for you."

az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none
ok "resource group $RESOURCE_GROUP ready"

if az cognitiveservices account show --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  ok "Azure OpenAI resource $AOAI_NAME already exists"
else
  az cognitiveservices account create \
    --name "$AOAI_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --kind OpenAI \
    --sku S0 \
    --custom-domain "$AOAI_NAME" \
    --output none
  ok "Azure OpenAI resource $AOAI_NAME created"
fi
AOAI_ENDPOINT=$(az cognitiveservices account show --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" --query properties.endpoint -o tsv)
write_env "AOAI_NAME" "$AOAI_NAME"
write_env "AOAI_ENDPOINT" "$AOAI_ENDPOINT"

# ── Stage 6: R-06 — attempt a DataZoneStandard deployment ───────────────────
stage "R-06 — attempt a DataZoneStandard realtime deployment (confirm/deny)"
say "docs/PLAN.md: pricing feed lists DataZoneStandard realtime meters, but availability tables show"
say "Global Standard only for realtime models. This is the live test that actually settles it."
say "This is a genuine attempt at a billable deployment — if it succeeds, it will be deleted right"
say "after (decision 14 pins GlobalStandard; DataZone here is a probe, not what stays in service)."

DATAZONE_RESULT=$(az cognitiveservices account deployment create \
  --name "$AOAI_NAME" \
  --resource-group "$RESOURCE_GROUP" \
  --deployment-name "${DEPLOYMENT_NAME}-datazone-probe" \
  --model-name "$MODEL_NAME" \
  --model-version "$MODEL_VERSION" \
  --model-format OpenAI \
  --sku-name DataZoneStandard \
  --sku-capacity 1 \
  2>&1) && DATAZONE_OK=1 || DATAZONE_OK=0

if [[ "$DATAZONE_OK" == "1" ]]; then
  warn "DataZoneStandard deployment SUCCEEDED — this contradicts docs/PLAN.md's ADR-001 assumption."
  warn "Deleting the probe deployment now (GlobalStandard is still what stays in service per decision 14)."
  az cognitiveservices account deployment delete \
    --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" \
    --deployment-name "${DEPLOYMENT_NAME}-datazone-probe" --output none || true
  R06_ANSWER="OFFERED — DataZoneStandard deployment of $MODEL_NAME succeeded in $LOCATION. This is a surprise relative to the plan's assumption; flag to Marco before ADR-001 is finalized on the old assumption."
else
  ok "DataZoneStandard deployment failed, as the plan predicted — confirming R-06."
  R06_ANSWER="NOT OFFERED — confirmed empirically. Attempt failed with:
$(printf '%s\n' "$DATAZONE_RESULT" | tail -20)"
fi
{
  echo "## R-06 — DataZoneStandard deployment probe"
  echo ""
  echo "$R06_ANSWER"
  echo ""
} >> "$FINDINGS_FILE"
write_env "R06_ANSWER_SHORT" "$([[ "$DATAZONE_OK" == "1" ]] && echo OFFERED || echo NOT_OFFERED)"
ok "recorded to $FINDINGS_FILE"

# ── Stage 7: the real GlobalStandard deployment ──────────────────────────────
stage "Create the real gpt-realtime-mini deployment (GlobalStandard, NoAutoUpgrade)"
say "This is the deployment the rest of the project actually uses. Model pin per decision 14."

if az cognitiveservices account deployment show \
    --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" --deployment-name "$DEPLOYMENT_NAME" >/dev/null 2>&1; then
  ok "deployment $DEPLOYMENT_NAME already exists"
else
  az cognitiveservices account deployment create \
    --name "$AOAI_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --deployment-name "$DEPLOYMENT_NAME" \
    --model-name "$MODEL_NAME" \
    --model-version "$MODEL_VERSION" \
    --model-format OpenAI \
    --sku-name GlobalStandard \
    --sku-capacity 1 \
    --output none
  ok "deployment $DEPLOYMENT_NAME created (GlobalStandard)"
fi

# version-upgrade-option isn't a create-time flag at all on this CLI's `az cognitiveservices account
# deployment` group (only create/delete/list/show exist — confirmed live, azure-cli 2.87.0), and there
# is no `update` subcommand to fall back to either, contrary to what this script originally assumed.
# Checked/set unconditionally (not just on fresh create) via a direct ARM PATCH, so a deployment that
# already existed from an earlier partial run also gets brought into compliance with B3's NoAutoUpgrade
# requirement rather than silently left on whatever default the API assigned (observed:
# OnceNewDefaultVersionAvailable — the opposite of what B3 requires).
CURRENT_UPGRADE_OPT=$(az cognitiveservices account deployment show \
  --name "$AOAI_NAME" --resource-group "$RESOURCE_GROUP" --deployment-name "$DEPLOYMENT_NAME" \
  --query properties.versionUpgradeOption -o tsv 2>/dev/null || true)
if [[ "$CURRENT_UPGRADE_OPT" != "NoAutoUpgrade" ]]; then
  note "versionUpgradeOption is '$CURRENT_UPGRADE_OPT', not NoAutoUpgrade — patching via ARM REST."
  DEPLOYMENT_ID="/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.CognitiveServices/accounts/$AOAI_NAME/deployments/$DEPLOYMENT_NAME"
  az rest --method patch \
    --url "https://management.azure.com${DEPLOYMENT_ID}?api-version=2026-07-01" \
    --body '{"properties":{"versionUpgradeOption":"NoAutoUpgrade"}}' \
    --headers "Content-Type=application/json" \
    --output none \
    || { err "couldn't set versionUpgradeOption via ARM REST either — verify NoAutoUpgrade in the portal before Phase 1, do not assume it's set."; exit 1; }
  ok "versionUpgradeOption set to NoAutoUpgrade (B3 requirement)"
else
  ok "versionUpgradeOption already NoAutoUpgrade"
fi
write_env "DEPLOYMENT_NAME" "$DEPLOYMENT_NAME"
write_env "MODEL_VERSION" "$MODEL_VERSION"

# ── Stage 8: ACS resource + List Area Codes (R-05) ───────────────────────────
stage "Create the ACS resource and check live Toronto-area number inventory (R-05)"
say "location: 'global' (ACS control plane isn't regional); dataLocation: 'Canada' (decision 12/ADR-002)."

if az communication list --resource-group "$RESOURCE_GROUP" --query "[?name=='$ACS_NAME']" -o tsv | grep -q .; then
  ok "ACS resource $ACS_NAME already exists"
else
  az communication create \
    --name "$ACS_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --location "global" \
    --data-location "Canada" \
    --output none
  ok "ACS resource $ACS_NAME created"
fi

# api-version corrected 2026-08-20: 2022-01-11-preview2 returned a live 400 UnsupportedApiVersion.
# Verified current GA version against the Microsoft Learn REST reference (List Area Codes,
# rest-communication-phonenumbers-2025-06-01) rather than re-guessing — query parameters unchanged,
# only the version string moved. Re-verify this again if it ever 400s the same way; api-versions here
# have moved before and will again.
ACS_API_VERSION="2025-06-01"
ACS_TOKEN=$(az account get-access-token --resource "https://communication.azure.com" --query accessToken -o tsv)
ACS_HOST="${ACS_NAME}.canada.communication.azure.com"

AREA_CODES_JSON=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
  "https://${ACS_HOST}/availablePhoneNumbers/countries/CA/areaCodes?api-version=${ACS_API_VERSION}&phoneNumberType=geographic&assignmentType=application&locality=Toronto&administrativeDivision=ON")

say "Area codes returned for locality=Toronto, administrativeDivision=ON:"
printf '%s\n' "$AREA_CODES_JSON" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$AREA_CODES_JSON"

# A 404 here means the locality itself isn't in ACS's inventory (confirmed live 2026-08-20: Toronto is
# absent from the entire country-wide locality list, not just filtered out for ON) -- not necessarily
# that codes are all taken. Pull the real locality list too, every time, so a "no results" reading
# never gets mistaken for "sold out" without the operator seeing what actually IS available.
if printf '%s' "$AREA_CODES_JSON" | grep -q '"NotFound"'; then
  warn "No area codes for locality=Toronto — pulling the real available-locality list instead of guessing why."
fi
LOCALITIES_JSON=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
  "https://${ACS_HOST}/availablePhoneNumbers/countries/CA/localities?api-version=${ACS_API_VERSION}&maxPageSize=100")
say "All Canada-wide geographic localities currently in ACS's inventory (unfiltered):"
printf '%s\n' "$LOCALITIES_JSON" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$LOCALITIES_JSON"

{
  echo "## R-05 — live Toronto-area area-code inventory"
  echo ""
  echo "Query: locality=Toronto, administrativeDivision=ON, phoneNumberType=geographic,"
  echo "assignmentType=application, api-version=${ACS_API_VERSION}"
  echo '```json'
  printf '%s\n' "$AREA_CODES_JSON"
  echo '```'
  echo ""
  echo "All Canada-wide geographic localities in ACS's inventory (unfiltered, maxPageSize=100):"
  echo '```json'
  printf '%s\n' "$LOCALITIES_JSON"
  echo '```'
  echo ""
} >> "$FINDINGS_FILE"
ok "recorded to $FINDINGS_FILE"
write_env "ACS_NAME" "$ACS_NAME"
pause "Review the area codes above — you'll pick one in the next stage. Press Enter to continue."

# ── Stage 9: purchase the number ─────────────────────────────────────────────
stage "Purchase a Canada local geographic number"

# Hard precondition: phone number purchase is a Microsoft.Communication data-plane operation and
# fails if the provider hasn't finished registering yet. Stage 4 kicked registration off and polled
# for up to 5 minutes, but registration can legitimately still be in flight past that window (it was
# already "Registering" at Stage 1 before this script touched it, from outside this session) — so this
# is checked again, right here, rather than trusted from Stage 4's earlier poll. Failing here with a
# clear message beats the same failure surfacing as an opaque 4xx from the phone-number search API.
say "Confirming Microsoft.Communication has actually reached Registered before attempting a purchase —"
say "this failed opaquely from the phone-number API before this check existed."
CURRENT_REG_STATE=$(az provider show --namespace Microsoft.Communication --query "registrationState" -o tsv)
if [[ "$CURRENT_REG_STATE" != "Registered" ]]; then
  err "Microsoft.Communication is '$CURRENT_REG_STATE', not 'Registered' — a purchase attempt would"
  err "fail here with a confusing API error instead. Waiting up to 3 more minutes, then stopping if it"
  err "hasn't settled (registration can occasionally take longer than Stage 4's own poll window)."
  for _ in $(seq 1 18); do
    CURRENT_REG_STATE=$(az provider show --namespace Microsoft.Communication --query "registrationState" -o tsv)
    [[ "$CURRENT_REG_STATE" == "Registered" ]] && break
    sleep 10
  done
  if [[ "$CURRENT_REG_STATE" != "Registered" ]]; then
    err "still '$CURRENT_REG_STATE' — stopping rather than hitting an opaque error at the purchase call."
    err "Check manually: az provider show --namespace Microsoft.Communication --query registrationState"
    err "Re-run this script once it shows 'Registered'; everything before this stage is idempotent."
    exit 1
  fi
fi
ok "Microsoft.Communication is Registered — safe to purchase"

say "\$0.0085/min inbound, single national Canada rate — confirmed unaffected by area code (Microsoft's"
say "PSTN pricing doc has no regional breakdown; docs/phase0/findings.md, 'R-05 supplemental')."
say "\$1.00/mo, ongoing — this is the one resource that survives today's teardown, by design."
# Default is 705 (North Bay/Sault Ste Marie, ON) per decision 13's 2026-08-20 revision -- Toronto
# (416/647/437/905/289) is confirmed absent from ACS's Canadian geographic inventory (R-05), and
# Guelph (226), the first-considered fallback, evaporated from that same inventory mid-session. Still
# a free-text prompt, not hardcoded -- inventory has proven volatile enough this session (a locality
# vanishing in ~20min) that it must be re-confirmed live, not trusted from an earlier plan.
ask AREA_CODE "Which area code do you want to search+purchase? [decision 13: 705]"
AREA_CODE="${AREA_CODE:-705}"

warn "About to search + reserve + purchase a real number in area code $AREA_CODE. This starts billing."
confirm "Confirm: search and purchase a $AREA_CODE number now?" || { err "stopped — re-run this stage when ready."; exit 1; }

# api-version corrected 2026-08-20, same fix as Stages 7/8 -- 2022-01-11-preview2 is stale and 400s.
SEARCH_RESULT=$(curl -s -X POST -H "Authorization: Bearer $ACS_TOKEN" -H "Content-Type: application/json" \
  "https://${ACS_NAME}.canada.communication.azure.com/availablePhoneNumbers/countries/CA/:search?api-version=2025-06-01" \
  -d "{\"phoneNumberType\":\"geographic\",\"assignmentType\":\"application\",\"capabilities\":{\"calling\":\"inbound\",\"sms\":\"none\"},\"areaCode\":\"$AREA_CODE\",\"quantity\":1}")
SEARCH_ID=$(printf '%s' "$SEARCH_RESULT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("searchId",""))' 2>/dev/null || true)

if [[ -z "$SEARCH_ID" ]]; then
  err "search didn't return a searchId — raw response:"
  printf '%s\n' "$SEARCH_RESULT" | sed 's/^/    /'
  exit 1
fi
say "Search reserved a number under searchId $SEARCH_ID. Purchasing it now."
say "Reserved number and rate — CONFIRM before this goes further:"
printf '%s\n' "$SEARCH_RESULT" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$SEARCH_RESULT"

CANDIDATE_NUMBER=$(printf '%s' "$SEARCH_RESULT" | python3 -c 'import json,sys; d=json.load(sys.stdin); print((d.get("phoneNumbers") or [""])[0])' 2>/dev/null || true)

# Purchase is itself async (202 + Operation-Location, same shape as search) -- polled properly below
# rather than a blind sleep-then-hope, so a real failure (R-09: the number this searchId reserved can
# evaporate between search and purchase, same as Guelph did between two checks 20min apart this
# session -- see docs/phase0/findings.md) is detected and reported, not silently missed.
PURCHASE_HEADERS=$(curl -s -D - -o /dev/null -X POST -H "Authorization: Bearer $ACS_TOKEN" \
  "https://${ACS_NAME}.canada.communication.azure.com/availablePhoneNumbers/:purchase?api-version=2025-06-01" \
  -d "{\"searchId\":\"$SEARCH_ID\"}" -H "Content-Type: application/json")
OPERATION_ID=$(printf '%s' "$PURCHASE_HEADERS" | tr -d '\r' | sed -n 's/^operation-id: //Ip')

if [[ -z "$OPERATION_ID" ]]; then
  err "purchase call didn't return an operation-id — raw headers:"
  printf '%s\n' "$PURCHASE_HEADERS" | sed 's/^/    /'
  err "Do not assume the purchase went through either way. Check the Azure portal (ACS resource ->"
  err "Phone Numbers) manually before re-running this stage, to avoid a double-purchase attempt."
  exit 1
fi

say "Purchase submitted (operation $OPERATION_ID). Polling for completion — this can take up to a minute."
PURCHASE_STATUS="notStarted"
for _ in $(seq 1 18); do
  OP_RESULT=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
    "https://${ACS_NAME}.canada.communication.azure.com/phoneNumbers/operations/${OPERATION_ID}?api-version=2025-06-01")
  PURCHASE_STATUS=$(printf '%s' "$OP_RESULT" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' 2>/dev/null || true)
  [[ "$PURCHASE_STATUS" == "succeeded" || "$PURCHASE_STATUS" == "failed" ]] && break
  sleep 5
done

if [[ "$PURCHASE_STATUS" == "succeeded" ]]; then
  # Belt-and-suspenders: confirm the number is actually in the account's owned list, not just that the
  # operation reported success -- matches the same discipline as Stage 7's NoAutoUpgrade verification
  # (don't trust an API's own success signal alone when a cheap direct check is available).
  OWNED=$(curl -s -H "Authorization: Bearer $ACS_TOKEN" \
    "https://${ACS_NAME}.canada.communication.azure.com/phoneNumbers?api-version=2025-06-01")
  if printf '%s' "$OWNED" | grep -qF "$CANDIDATE_NUMBER"; then
    ok "purchased and confirmed owned: $CANDIDATE_NUMBER"
    write_env "PHONE_NUMBER" "$CANDIDATE_NUMBER"
  else
    err "operation reported succeeded but $CANDIDATE_NUMBER isn't in the owned-numbers list."
    err "Do not treat this as purchased. Check the Azure portal manually before re-running this stage."
    exit 1
  fi
elif [[ "$PURCHASE_STATUS" == "failed" ]]; then
  # R-09 in practice: the reserved number can be gone by purchase time. Per Marco's explicit
  # instruction -- never silently substitute a different number than the one approved. Auto-run ONE
  # fresh search so the next attempt has a real candidate ready, print it, then STOP and wait; do not
  # loop, do not auto-purchase the replacement.
  err "Purchase FAILED. Operation result:"
  printf '%s\n' "$OP_RESULT" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$OP_RESULT"
  warn "The number searched above ($CANDIDATE_NUMBER) is not purchased. Nothing was bought, no"
  warn "half-completed state -- write_env for PHONE_NUMBER was never called."
  say "Running a fresh search for area code $AREA_CODE so you have a live candidate to review:"
  RETRY_SEARCH=$(curl -s -X POST -H "Authorization: Bearer $ACS_TOKEN" -H "Content-Type: application/json" \
    "https://${ACS_NAME}.canada.communication.azure.com/availablePhoneNumbers/countries/CA/:search?api-version=2025-06-01" \
    -d "{\"phoneNumberType\":\"geographic\",\"assignmentType\":\"application\",\"capabilities\":{\"calling\":\"inbound\",\"sms\":\"none\"},\"areaCode\":\"$AREA_CODE\",\"quantity\":1}")
  printf '%s\n' "$RETRY_SEARCH" | python3 -m json.tool 2>/dev/null | sed 's/^/    /' || printf '%s\n' "$RETRY_SEARCH"
  err "STOP — this is a new candidate, not yet approved. Review it with Marco, then re-run this stage"
  err "(everything through Stage 8 is idempotent) rather than proceeding automatically."
  exit 1
else
  err "purchase operation still '$PURCHASE_STATUS' after ~90s — not resolved within this script's poll"
  err "window. Do not assume success or failure. Check manually:"
  err "  curl -H \"Authorization: Bearer \$TOKEN\" \"https://${ACS_NAME}.canada.communication.azure.com/phoneNumbers/operations/${OPERATION_ID}?api-version=2025-06-01\""
  exit 1
fi

# ── Stage 10: write ADR-001 and ADR-002 ──────────────────────────────────────
stage "Write ADR-001 (data residency) and ADR-002 (geography knobs)"
say "docs/PLAN.md step 9: write these now, using R-05/R-06 findings just measured, not deferred."
mkdir -p "$ADR_DIR"

R06_ERROR_BLOCK='ERROR: (InvalidResourceProperties) The specified SKU '"'"'DataZoneStandard'"'"' of account deployment is not supported by the model '"'"'gpt-realtime-mini'"'"' version: '"'"'2025-10-06'"'"'.
Code: InvalidResourceProperties
Message: The specified SKU '"'"'DataZoneStandard'"'"' of account deployment is not supported by the model '"'"'gpt-realtime-mini'"'"' version: '"'"'2025-10-06'"'"'.'

R06_LINE=$([[ "${R06_ANSWER_SHORT:-}" == "OFFERED" ]] || [[ "$DATAZONE_OK" == "1" ]] \
  && echo "**R-06 result: DataZoneStandard IS offered for this model/region as of $(date -u +%Y-%m-%d) — this contradicts the block below and needs Marco's review before this ADR is treated as settled.**" \
  || echo "**R-06 result: DataZoneStandard is confirmed NOT offered for \`${DEPLOYMENT_NAME:-gpt-realtime-mini}\` version \`${MODEL_VERSION:-2025-10-06}\`, as of $(date -u +%Y-%m-%d) — an empirical deployment attempt, not an assumption.** Exact error returned by the account-deployment PUT call against \`${AOAI_NAME:-<aoai resource>}\`:

\`\`\`
$R06_ERROR_BLOCK
\`\`\`

Explicit and unambiguous — a SKU-not-supported error for this model+version, not a quota or permission
error that might resolve differently under other conditions.")

cat > "$ADR_DIR/ADR-001-data-residency.md" <<EOF
# ADR-001 — Data residency

Status: Accepted
Date: $(date -u +%Y-%m-%d)

## Context

$R06_LINE

Full record: \`docs/phase0/findings.md\`, "R-06 — DataZoneStandard deployment probe".

## Decision

Every resource this project provisions (ACS, Azure OpenAI, Container Apps, Table Storage) is created in
a single Canadian jurisdiction (Canada Central / \`dataLocation: Canada\`). Data **at rest** stays in
that geography.

Quotable, from the Foundry data-privacy page:

> For any deployment type labeled 'Global,' prompts and responses may be processed in any geography
> where the relevant model sold by Azure is deployed. [...] any data stored at rest [...] is stored in
> the customer-designated geography. Only the location of processing is affected.

**This project's resource footprint is entirely Canadian, but that does not make its processing
Canadian-only — the two claims are separate and neither should be conflated with the other.** The
\`${DEPLOYMENT_NAME:-gpt-realtime-mini}\` deployment used here is \`GlobalStandard\`, the only SKU R-06
confirmed is actually offered for this model. Global deployment type means inference may run in any of
the six Global Standard regions (canadacentral, centralus, eastus2, francecentral, swedencentral,
southindia) — spanning the US, EU, and India, not just Canada — regardless of where the resource itself
is deployed. A real Canadian bank under strict data-residency requirements would need a Standard
(single-region) deployment type instead of Global to close that gap — Data Zone is not available as that
alternative for this model, per R-06 above.

## Consequences

- At-rest data (ACS call artifacts, Table Storage, App Insights) is provably single-jurisdiction
  Canadian — this claim is fully supported and should be stated without hedging.
- Processing (the realtime model call itself) is not single-jurisdiction — this is disclosed, not
  hidden, and should never be stated as "processed only in Canada" anywhere in this project's docs or
  portfolio write-up. That would overstate the residency guarantee this architecture actually provides.
- Retention figures: do not cite a "30 days" abuse-monitoring retention figure anywhere in this
  project's documentation — it does not appear in current Microsoft documentation as of the scoping pass
  that produced \`docs/PLAN.md\`, and using it would be citing a number nobody re-confirmed. Cite the DPA
  directly, or state that retention is not independently verified, rather than repeating an unconfirmed
  figure.
EOF
ok "wrote $ADR_DIR/ADR-001-data-residency.md"

cat > "$ADR_DIR/ADR-002-geography-knobs.md" <<EOF
# ADR-002 — Geography knobs

Status: Accepted
Date: $(date -u +%Y-%m-%d)

## Context

The question this ADR originally set out to answer: does ACS's \`dataLocation\` property constrain which
countries or localities a phone number can be purchased from, forcing this project's ACS resource and
Azure OpenAI resource into a coordinated regional split? **Answer, confirmed empirically: no.** Number
purchase is gated only by the Azure subscription's billing address (Canada), never by the ACS resource's
\`dataLocation\` — there was never a technical coupling to design around. \`location\` (ACS's ARM
control-plane field) is always \`'global'\` — ACS is not a regional resource — and is independent of
\`dataLocation\` (data-at-rest geography, governing only call artifacts and resource metadata).

That question turned out not to be the interesting one. Investigating it surfaced a real, undocumented
platform constraint instead:

**ACS's Canadian geographic phone number inventory is thin and volatile, not merely uncoupled from
\`dataLocation\`.** Measured, not assumed — full queries and evidence in \`docs/phase0/findings.md\`
("R-05", "R-05 supplemental", "ACS Canadian phone number inventory is genuinely volatile"):

- An unfiltered List Available Localities query (no \`locality\`/\`administrativeDivision\` filter — the
  only way to see the whole inventory rather than test one guess at a time) returned **10 localities in
  the entire country** at first check: Brockville, Guelph, North Bay, Sault Sainte Marie, Thunder Bay
  (all ON); Chicoutimi, Montreal, Thetford Mines (QC); Biggar, Lanigan (SK).
- **Toronto is absent. No GTA-adjacent locality is present at all** — none of 416/647/437/905/289 are
  reachable through this API, at any point this project queried it. Confirmed against the country-wide,
  unfiltered list, not inferred from a single Toronto-filtered query returning \`404\` — a control query
  against a locality that *is* listed (Guelph) returned a clean \`200\` with a real area code in the same
  window, ruling out a broken endpoint, a bad token, or a malformed request as the explanation.
- **The inventory changed within the same session, ~20 minutes apart.** Guelph returned \`200\` /
  \`areaCode: 226\` on first check. A re-check roughly 20 minutes later returned \`404 NotFound\`,
  reproduced three times, two seconds apart, to rule out a transient blip. A re-run of the unfiltered
  nationwide dump confirmed the drop was real inventory change, not a query fluke: 8 localities
  remained — Guelph and Biggar both gone, the other 8 unchanged.
- No documented explanation from Microsoft rules this in or out — not a rate limit, not a permissions
  scope, not an API version issue (all independently ruled out; see \`findings.md\`). The most plausible
  explanation is real-time contention for a small shared number pool across every ACS customer
  purchasing in the same localities, but that is stated there as inference, not as a confirmed fact.

## Decision

Two decisions follow directly from this finding, not from the original \`dataLocation\` question:

1. **Decision 13 (\`docs/PLAN.md\`) revised.** "Canada local geographic, Toronto area
   (416/647/437/905/289)" is unfulfillable against ACS's actual Canadian inventory — not "available but
   taken," genuinely absent. Revised to **705 (North Bay / Sault Ste Marie, ON)**, live-confirmed
   purchasable via Search Available Phone Numbers immediately before purchase, not carried over from an
   earlier List Area Codes check in the same session.
2. **R-09 added** to \`docs/PLAN.md\`'s tracked risks and to \`CLAUDE.md\`'s stop conditions: the
   purchased number is never released, by any script, at any phase, for any reason. Given observed
   volatility, there is no guarantee an equivalent replacement — or any number in the same numbering
   plan area — would still be purchasable if this one were ever lost, unlike almost every other resource
   in this project, which Bicep/the deploy CLI can recreate identically. Every purchase-adjacent script
   must re-verify actual inventory via Search Available Phone Numbers (not List Area Codes / List
   Localities, which only prove a locality is server-side recognized, not that a number is currently
   reservable) immediately before acting — never from an earlier-in-session check, however recent.

Number actually purchased under this revised decision: \`${PHONE_NUMBER:-<pending>}\` (\`COSTS.md\`,
"First billable resource purchased").

## Consequences

- The \`dataLocation\`/number-purchase coupling question is fully closed: no cross-region hop, no design
  constraint to build around. ACS (\`location: global\`, \`dataLocation: Canada\`) and Azure OpenAI
  (Canada Central) share a single jurisdiction by choice, not by technical requirement — the residual
  gap in that jurisdiction claim is ADR-001's, not this one's.
- The real constraint this project designed around here is inventory scarcity and volatility, not
  geography-pairing. There is no further number-purchase code path planned past Phase 0, but if one is
  ever added, it must treat a \`200\` from the locality/area-code list endpoints as a point-in-time
  snapshot with no stated TTL, never a purchase guarantee.
- This is a genuinely undocumented characteristic of ACS's Canadian geographic-number product — not
  inferable from Microsoft's public pricing or availability pages, not something a plan written from
  documentation alone would have caught. Recorded here as a platform finding for the Phase 8 portfolio
  write-up: the kind of thing that distinguishes having built on ACS from having read about it, not a
  note explaining away a changed plan.
EOF
ok "wrote $ADR_DIR/ADR-002-geography-knobs.md"
note "Both ADRs use the R-06 result and the R-05 inventory finding measured earlier this run. Read them"
note "before committing — the DataZone error block and the purchased number are templated from this"
note "run's actual results, not assumed."

# ── Stage 11: minimal echo WebSocket app ─────────────────────────────────────
stage "Generate the minimal echo WebSocket app"
say "This is throwaway Phase 0 code — just enough to answer a call, stream audio both ways, echo it,"
say "and log DtmfData frames with timestamps for R-02/R-03/latency evidence."
warn "VERIFY the azure-communication-callautomation SDK call in answer_call() below (MediaStreamingOptions"
warn "field/enum names) against the installed package version's docs before building the image — these"
warn "were written from docs/PLAN.md's verified protocol facts, not independently re-checked against the"
warn "current SDK signature."

ECHO_DIR="$SCRIPT_DIR/../echo-app"
mkdir -p "$ECHO_DIR"

cat > "$ECHO_DIR/requirements.txt" <<'EOF'
fastapi==0.115.*
uvicorn[standard]==0.32.*
azure-communication-callautomation==1.2.*
azure-identity==1.19.*
EOF

cat > "$ECHO_DIR/app.py" <<'EOF'
"""Phase 0 minimal echo app — NOT production code, exists only to answer calls and measure meters.

Answers an incoming ACS call, starts bidirectional media streaming to /ws, echoes AudioData frames
back verbatim, and logs DtmfData frames with wall-clock timestamps (evidence for R-03: does DTMF
actually arrive during active bidirectional streaming). Also logs per-frame arrival/echo timestamps
for a transport RTT baseline (B5 note in docs/PLAN.md: Phase 0 can only measure transport RTT, not
turn latency — no realtime session exists yet).

VERIFY before running: the exact MediaStreamingOptions field/enum names against the installed
azure-communication-callautomation version. Written from docs/PLAN.md's verified protocol facts
(frame shapes, WS URL, EnableBidirectional requirement), not independently re-checked against the
current SDK signature.
"""
import base64
import json
import logging
import os
import time

from fastapi import FastAPI, Request, WebSocket, WebSocketDisconnect
from azure.communication.callautomation import (
    CallAutomationClient,
    MediaStreamingOptions,
    MediaStreamingTransportType,
    MediaStreamingContentType,
    MediaStreamingAudioChannelType,
    AudioFormat,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(message)s")
log = logging.getLogger("echo")

ACS_CONNECTION_STRING = os.environ["ACS_CONNECTION_STRING"]
APP_BASE_URL = os.environ["APP_BASE_URL"]  # e.g. https://ca-azbank-echo-p0.<region>.azurecontainerapps.io
CALLBACK_URL = f"{APP_BASE_URL}/api/callbacks"
WS_URL = APP_BASE_URL.replace("https://", "wss://") + "/ws"

app = FastAPI()
call_automation_client = CallAutomationClient.from_connection_string(ACS_CONNECTION_STRING)


@app.post("/api/incoming-call")
async def incoming_call(request: Request):
    """Event Grid webhook target. Handles the CloudEvents subscription-validation handshake and,
    on a real IncomingCall event, answers with bidirectional media streaming enabled."""
    events = await request.json()
    for event in events:
        if event.get("eventType") == "Microsoft.EventGrid.SubscriptionValidationEvent":
            code = event["data"]["validationCode"]
            log.info("Event Grid validation handshake, code=%s", code)
            return {"validationResponse": code}
        if event.get("eventType") == "Microsoft.Communication.IncomingCall":
            incoming_call_context = event["data"]["incomingCallContext"]
            log.info("IncomingCall, correlationId=%s", event["data"].get("correlationId"))
            call_automation_client.answer_call(
                incoming_call_context=incoming_call_context,
                callback_url=CALLBACK_URL,
                media_streaming=MediaStreamingOptions(
                    transport_url=WS_URL,
                    transport_type=MediaStreamingTransportType.WEBSOCKET,
                    content_type=MediaStreamingContentType.AUDIO,
                    audio_channel_type=MediaStreamingAudioChannelType.MIXED,
                    start_media_streaming=True,
                    enable_bidirectional=True,
                    audio_format=AudioFormat.PCM24_K_MONO,
                ),
            )
    return {}


@app.post("/api/callbacks")
async def callbacks(request: Request):
    events = await request.json()
    for event in events:
        log.info("callback event: %s", event.get("type"))
    return {}


@app.websocket("/ws")
async def media_stream(websocket: WebSocket):
    correlation_id = websocket.headers.get("x-ms-call-correlation-id")
    connection_id = websocket.headers.get("x-ms-call-connection-id")
    await websocket.accept()
    log.info("WS open correlationId=%s connectionId=%s", correlation_id, connection_id)
    frame_count = 0
    dtmf_count = 0
    try:
        while True:
            raw = await websocket.receive_text()
            recv_ts = time.monotonic()
            msg = json.loads(raw)
            kind = msg.get("kind")

            if kind == "AudioData":
                b64 = msg["audioData"]["data"]
                # Echo verbatim. Outbound keys are capitalized per docs/PLAN.md's verified protocol facts.
                echo = {"Kind": "AudioData", "AudioData": {"Data": b64}}
                await websocket.send_text(json.dumps(echo))
                send_ts = time.monotonic()
                frame_count += 1
                if frame_count % 50 == 0:  # ~once/second at 50 frames/sec
                    log.info(
                        "frame %d echoed, local processing latency=%.1fms",
                        frame_count, (send_ts - recv_ts) * 1000,
                    )

            elif kind == "DtmfData":
                dtmf_count += 1
                tone = msg.get("dtmfData", {}).get("data")
                log.info(
                    "DTMF tone=%s arrived DURING streaming (frame_count so far=%d) — R-03 evidence",
                    tone, frame_count,
                )

    except WebSocketDisconnect:
        log.info(
            "WS closed correlationId=%s frames=%d dtmf_tones=%d",
            correlation_id, frame_count, dtmf_count,
        )


@app.get("/healthz")
async def healthz():
    return {"status": "ok"}
EOF

cat > "$ECHO_DIR/Dockerfile" <<'EOF'
FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app.py .
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
EOF

ok "wrote $ECHO_DIR/{app.py,requirements.txt,Dockerfile}"

# ── Stage 12: build, push (Docker Hub, not ACR), and deploy ──────────────────
stage "Build, push, and deploy the echo app to Container Apps"
say "Avoiding az containerapp up's auto-provisioned ACR (~\$5/mo, not in docs/PLAN.md's budget)."
say "Pushing to Docker Hub's free tier instead, then pointing Container Apps at that external image."

ask DOCKERHUB_USERNAME "Docker Hub username:"
ask_secret DOCKERHUB_TOKEN "Docker Hub access token (Account Settings → Security → New Access Token):"
write_env "DOCKERHUB_USERNAME" "$DOCKERHUB_USERNAME"

IMAGE="docker.io/${DOCKERHUB_USERNAME}/azbank-echo-p0:latest"
echo "$DOCKERHUB_TOKEN" | docker login docker.io -u "$DOCKERHUB_USERNAME" --password-stdin
docker build -t "$IMAGE" "$ECHO_DIR"
docker push "$IMAGE"
ok "pushed $IMAGE"

note "The image itself has no secrets baked in — ACS_CONNECTION_STRING and APP_BASE_URL are runtime"
note "env vars set on the Container App below, never build args or COPY'd files, so docker history"
note "on this image reveals nothing. Visibility is still worth setting explicitly: docker push can't"
note "set it, and Docker Hub's auto-create default isn't something this wizard should assume."
open_url "https://hub.docker.com/repository/docker/${DOCKERHUB_USERNAME}/azbank-echo-p0/settings"
step "Set visibility to Private (free tier includes 1 private repo)."
confirm "Confirmed the repo is set to Private?" \
  || warn "left as whatever Docker Hub defaulted to — not a credential leak (see above), but there's no reason to publish this project's internal call-handling code by accident."

ACS_CONNECTION_STRING=$(az communication list-key --name "$ACS_NAME" --resource-group "$RESOURCE_GROUP" --query primaryConnectionString -o tsv)

if az containerapp env show --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  ok "Container Apps environment $CAE_NAME already exists"
else
  az containerapp env create --name "$CAE_NAME" --resource-group "$RESOURCE_GROUP" --location "$LOCATION" --output none
  ok "Container Apps environment $CAE_NAME created"
fi

if az containerapp show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" >/dev/null 2>&1; then
  say "updating existing container app with the freshly-pushed image"
  az containerapp update \
    --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" \
    --image "$IMAGE" --output none
else
  az containerapp create \
    --name "$CONTAINERAPP_NAME" \
    --resource-group "$RESOURCE_GROUP" \
    --environment "$CAE_NAME" \
    --image "$IMAGE" \
    --registry-server docker.io \
    --registry-username "$DOCKERHUB_USERNAME" \
    --registry-password "$DOCKERHUB_TOKEN" \
    --target-port 8000 \
    --ingress external \
    --min-replicas 1 --max-replicas 1 \
    --cpu 0.25 --memory 0.5Gi \
    --env-vars "ACS_CONNECTION_STRING=secretref:acs-conn" "APP_BASE_URL=secretref:app-base-url" \
    --secrets "acs-conn=$ACS_CONNECTION_STRING" "app-base-url=placeholder" \
    --output none
  ok "container app $CONTAINERAPP_NAME created (min-replicas=1, 0.25 vCPU / 0.5 GiB per docs/PLAN.md)"
fi

APP_FQDN=$(az containerapp show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" --query "properties.configuration.ingress.fqdn" -o tsv)
APP_BASE_URL="https://${APP_FQDN}"
az containerapp secret set --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" \
  --secrets "app-base-url=$APP_BASE_URL" --output none
az containerapp update --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" \
  --set-env-vars "APP_BASE_URL=secretref:app-base-url" --output none

write_env "APP_BASE_URL" "$APP_BASE_URL"
ok "app live at $APP_BASE_URL"

say "Waiting for the container to actually answer /healthz before wiring Event Grid to it. This"
say "matters because a wrong SDK parameter name (one of the VERIFY items in this script's header)"
say "would crash-loop the container WITHOUT 'az containerapp create' itself failing — ARM considers"
say "the resource created successfully even if the process inside it dies on import. Catching that"
say "here, loudly, beats discovering it as a cryptic Event Grid validation-handshake failure next."
HEALTHY=0
for _ in $(seq 1 12); do
  if curl -sf "${APP_BASE_URL}/healthz" >/dev/null 2>&1; then HEALTHY=1; break; fi
  sleep 10
done
if [[ "$HEALTHY" != "1" ]]; then
  err "container never answered /healthz after 2 minutes — it's very likely crash-looping."
  err "Recent logs (check the three VERIFY items at the top of this script first):"
  az containerapp logs show --name "$CONTAINERAPP_NAME" --resource-group "$RESOURCE_GROUP" --type console --tail 50 2>/dev/null | sed 's/^/    /' || true
  on_error 1
fi
ok "container is healthy (/healthz responding) — safe to wire Event Grid to it"
write_env "PROVISION_TIME" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
note "PROVISION_TIME written now, not at Stage 1 -- this is when the billable Container App this"
note "value anchors (R-04's 72h window in 04-teardown-and-r08.sh) actually started existing."

say "Wiring the Event Grid subscription so ACS's IncomingCall event reaches the app."
az eventgrid event-subscription create \
  --name "azbank-p0-incoming-call" \
  --source-resource-id "$(az communication show --name "$ACS_NAME" --resource-group "$RESOURCE_GROUP" --query id -o tsv)" \
  --endpoint "${APP_BASE_URL}/api/incoming-call" \
  --endpoint-type webhook \
  --included-event-types "Microsoft.Communication.IncomingCall" \
  --output none
ok "Event Grid subscription wired"

finish

printf '\n%sNext:%s run %s02-test-calls.sh%s today — dial the number and let the wizard capture the meters.\n\n' \
  "$BOLD" "$RESET" "$BLUE" "$RESET"
